### ISSUE TITLE
testdox doesn't show dataProvider entries

### ISSUE THREAD

**Issue by trichins** [sebastianbergmann/phpunit#1098]
I have a test function that has @dataProvider in the comments.  When I run it without testdox, I see one dot for each of the data entries.  But with testdox, all I see is one run.  I found http://www.twisty.com/bandwagon/archives/2011/07/16/141959 where it talks about how phpunit used to do this but then it changed years ago.  The line number that needs to change is 255 but the fix is still correct.

Was it intentional to remove this functionality or was it just inadvertent?

**Comment by jessiehernandez** [comment]
I too want this to be merged in. I name my tests as "business rules", then generate a TestDox document so that I can provide management with the business rules currently implemented in the code. There are cases when an action needs to be taken for multiple values. Instead of writing a test for each value, I use a @dataProvider and just one test method. In this case the business rule becomes vague, as the actual value being tested does not come up in the TestDox output.

**Comment by omoon** [comment]
+1

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
