### ISSUE TITLE
Decide what to do with assertTag() and assertSelect*().

### ISSUE THREAD

**Issue by whatthejeff** [sebastianbergmann/phpunit#1292]
These assertions are simply broken. For reference, see:

 * #1278
 * #1158
 * #995
 * #878
 
The implementation is also quite poor. Most notably:

 * The CSS selector parser is not proper.
   * It doesn't comply to any known CSS specification.
   * It doesn't specify which features it intends to support and which it doesn't.
   * It doesn't validate syntax, fail or report errors.
 * The node selecting is done by recursively walking through the DOM in userland which is inefficient when compared to something more conventional like XPath.
 * The CSS node selecting functionality is done in reverse which makes it effectively broken for combinators (see: #878).
 
My opinion is that the implementations for these features should be replaced by something like [symfony/DomCrawler](https://github.com/symfony/DomCrawler). Personally, I would like to see these features deprecated in core and ported to a 3rd-party plugin as the current APIs are cumbersome and unintuitive–but I understand that might not be practical.

**Comment by whatda** [comment]
There haven't been any updates for months now... assertTag of whatthejeff's package is still not implemented (see https://github.com/phpunit/phpunit-dom-assertions/issues/3).

I think it was a bad idea to remove the assertions. They should rather have seen bugfixes or at least been ported to a separate package.

Our problem now is that we need to use an old version of PHPUnit, since we depend on assertTag and IMO there aren't any good alternatives.

Nevertheless, thanks for your efforts and have a nice day.
