### ISSUE TITLE
Global Mock Object Matcher

### ISSUE THREAD

**Issue by jonmchan** [sebastianbergmann/phpunit#1454]
According to docs:

> Note
> The $index parameter for the at() matcher refers to the index, starting at zero, in all method invocations  for a given mock object. 

Is there a Matcher that has an index that is matched across all mocked objects instead of just a single mocked object?

I'm interesting in mocking multiple services and ensure they all are executed in a certain order such as in this example:

```php
class ProcessManager {
    // injected via DI
    protected $service1;
    protected $service2;
    protected $service3;

    public function run() {
        $service1->execute();
        $service2->execute();
        $service3->execute();
    }
}
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.

**Comment by elnur** [comment]
Any progress on this?

**Comment by sebastianbergmann** [comment]
`at()` no longer exists.

**Comment by elnur** [comment]
Whatcha mean? I see it here: https://phpunit.readthedocs.io/en/9.5/test-doubles.html#test-doubles-mock-objects-tables-matchers

Though my question was about being able to test the order of method calls across mock objects. Is there anything for that? I'd hate to have to switch to Mockery just because of this single missing feature.
