### ISSUE TITLE
--exlcude-group commandline option should work in addition to group/exclude setting in phpunit.xml

### ISSUE THREAD

**Issue by andig** [sebastianbergmann/phpunit#1664]
This issue is on a similar line as https://github.com/sebastianbergmann/phpunit/issues/322 but related to excluding.

The `--exclude--group` command line option does (up to 4.4) override the `<group><exclude></group>` setting. 
IMHO instead it should add **additional** groups for exclusion (cumulative usage). Otherwise it takes away the ability to define default exclusions.

Example: our build job https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/56731384 fails because the phpunit.xml-excluded `fontsrequired` group is included again when `--exclude-group aggregation` is defined.

**Comment by andig** [comment]
Maybe I've raised this the wrong way- if so please let me know ;)

**Comment by jmcclell** [comment]
Overriding is better.

I'll give you an example. Let's say I need to test against two versions of a dependency and so I have tests that break between those two versions taged as "dep1" and "dep2" for v1 and v2. As my default behavior for phpunit, I want to exclude dep1 because locally I use dep2. But, I need my CI to be able to test dep1 without dep2, so I have it pass "--exclude-group dep2" which replaces what I've got.

Otherwise, I have to use --include-group dep1 --exclude-group dep2 and hope that include takes precdence over exclude?

In your case, all you need to do is re-apply your default behavior and the additional groups. Perhaps there could be "--add-exclude-group" to do what you want?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
