### ISSUE TITLE
Add method() to interface PHPUnit_Framework_MockObject_MockObject

### ISSUE THREAD

**Issue by Vinai** [sebastianbergmann/phpunit#1680]
Since phpunit 4 (or so) it is possible to omit the first part of the call chain when stubbing methods on mocks. For example, instead of
```php
$mock->expects($this->any())->method('method_name')->will...
```
the following can be used:
```php
$mock->method('method_name')->will...
```

This works fine and is easier to read, but the IDE isn't happy with it because the `PHPUnit_Framework_MockObject_MockObject` interface doesn't have the `method` method. For that reason it marks the second code snippet with a "method not found" warning.
Do you have any thoughts on adding the method to the mock object interface?

I realize it would force all third party implementations to add the method to their implementation, too. I can't judge how much of an issue that would be.

**Comment by sebastianbergmann** [comment]
The problem here is that the `method` method is only added to a test double when the original class does not have a method named `method`. And since the signature of the method named `method` in that original class most likely does not match the one of mock object API: boom.

I recently discussed this issue with @mikhailvink of JetBrains. They will likely add some "magic" to PhpStorm to enable what you want to do without the method named `method` being part of the interface.

Please note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.

**Comment by Vinai** [comment]
Awesome, thanks!

**Comment by MaXal** [comment]
We would like not to add any "magic" because "magic" tends to be obsolete in a couple of months/years and it's hard to keep it up to date. Also it's not possible to patch PhpStorm for all framework and all possible PHP magic.

The possible way to solve the issue from a PHPUnit side is to add 
``@method PHPUnit_Framework_MockObject_Builder_InvocationMocker method($constraint)``
annotation to ``PHPUnit_Framework_MockObject_MockObject`` interface. This will clearly states for other developers and for PhpStorm that the instances of the interface provide such method.

**Comment by tim-bezhashvyly** [comment]
Can confirm that the issue is solved in PHPStorm 9.

**Comment by Ig0r-M** [comment]
PHPStorm still not happy about this although there is annotation in interface.
