### ISSUE TITLE
Throwables in tests

### ISSUE THREAD

**Issue by kelunik** [sebastianbergmann/phpunit#1765]
If there's something like a `ParseError` or any other `Error`, the type hint fails with PHP 7.

```
TypeError: Argument 1 passed to PHPUnit_Framework_TestCase::onNotSuccessfulTest() must be an instance of Exception, instance of ParseError given, called in Framework/TestCase.php on line 851. 
```

**Comment by GrahamCampbell** [comment]
I think this is a duplicate.

**Comment by kelunik** [comment]
There's #1748, but that's specific to `@expectedException`.

**Comment by cabernet-zerve** [comment]
I believe that this should have been part of #1748, and it seems like the 'proper' fix is to change the type hint on onNotSuccessfulTest from Exception to Throwable, but I think that that breaks BC pretty badly.

Likely the best option would be to remove the type hint and perhaps do inline version-specific testing for Throwable in PHP_MAJOR_VERSION >=7 and Exception otherwise, not sure?

**Comment by GrahamCampbell** [comment]
> but I think that that breaks BC pretty badly.

Potentially a change for version 5.0 then which isn't too far a off a release. A few months I believe.

**Comment by cabernet-zerve** [comment]
Just created pull request #1766 for this
