### ISSUE TITLE
Add support for deep-cloning of results passed between tests using @depends

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1780]
Since PHPUnit 3.4 the following is supported

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $o = new StdClass;

        // ...

        return $o;
    }

    /**
     * @depends testOne
     */
    public function testTwo($o)
    {
    }
}
```

to indicate that 1) the execution of `testTwo` should be skipped in case the execution of `testOne` fails and 2) that the variable returned from `testOne` should be passed on to `testTwo` as an argument.

Until now the variable is passed "as-is" meaning that for objects, for instance, a reference to the original object returned from `testOne` is passed on. This is not desired in all situations, for instance when multiple tests depend on the same test thus all working with the same object that was returned by the test they depend on.

It should be possible to clone an object that is passed to a depending test like this:

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $o = new StdClass;

        // ...

        return $o;
    }

    /**
     * @depends clone testOne
     */
    public function testTwo($o)
    {
    }
}
```

**Comment by Nahasean94** [comment]
This doesnt seem to be working in my code
`
use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../src/Stack.php';

class StackTest extends TestCase {
  /**
   * @depends testHello
   */
  public function testname($obj) {
    $this->assertEquals('Sea', $obj->name());

  }

  public function testHello() {
    $ss = new Stack();
    $this->assertEquals(TRUE, is_object($ss));
    return $ss;
  }
}`
The above code passes and it should fail because the method `name()` in `Stack` class returns `Sean` and not `Sea`
