### ISSUE TITLE
Support Hack annotations in addition to docblock comments

### ISSUE THREAD

**Issue by fredemmott** [sebastianbergmann/phpunit#1784]
I'm happy to implement this, just want to get some feedback on the idea before spending the time to make a PR.

I generally dislike comments being more than comments, even if they are structured. Under HHVM, I'd like to support

```Hack
// As attributes don't support namespacing, just 'requires()' seems likely to cause problems
<<expectedException('MyExceptionClass'), requiresTest('testBar')>>
function testFoo() {
}
```

Is this something you'd be interested in as a PR, assuming that it didn't break existing docblock support, and only checked attributes under HHVM?

**Comment by sebastianbergmann** [comment]
Do you plan to propose (and implement) this feature for PHP, too? Now would be the time to draft an RFC for PHP 7.1. Please understand that I am reluctant to add Hack-only features to PHPUnit.

**Comment by fredemmott** [comment]
No; while I believe the general concept is  supported, based on past discussions of attributes/annotations on php-internals I don't think any specific implementation would be likely to get the 2/3rds vote required. Trying doesn't seem like a good use of time.

**Comment by krakjoe** [comment]
When an RFC is refused, it's never a waste of time, it's valuable research. 

When a discussion is going nowhere, it's because someone isn't listening, it's usually the person who started the discussion. There is usually a reluctance to change implementations to suit the popular opinion of the group and a preference to argue the case for your implementation.

If it weren't for past discussions and RFC's on this subject, you would not know that the concept in general has support.

Look on the past RFC's and discussions as research that has been done for you, for free. Try to address every legitimate concern raised in those discussions, don't re-implement a past patch in the hope people have changed their minds; They haven't, they are just not talking about it today.

If you do all that, and you still get a "No", it's not a waste of time, it's more valuable research and you, or someone else, can try again.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
