### ISSUE TITLE
Is there any way to make a tests for asynchronous functions?

### ISSUE THREAD

**Issue by westtrade** [sebastianbergmann/phpunit#1813]
Dear Sebastian Bergmann.

I try to make tests for asynchronous functions, like PHP EIO functions and for phpDaemon library. 

Is there less painfull methods to implement ending callback in test for it?

Thank you for attention!

**Comment by henriquemoody** [comment]
To test IO functions you can use [vfsStream](https://github.com/mikey179/vfsStream). I think it's quoted on PHPUnit's documentation.

When I start developing [Arara\Process](https://github.com/Arara/Process), which has a lot of calls to [PCNL](http://php.net/pcntl) and [POSIX](http://php.net/posix) functions, my first thought was to [overwrite the functions in the namespace](http://php.net/manual/en/language.namespaces.fallback.php) but that come with somes problems:

- I had to overwrite the same functions in more than one namespace
- I had to use the same functions in more than one test case in the same namespace
- It was messy

Then I started to looking for some way to mock PHP functions, and I found:

- [APD](http://php.net/apd)
- [MockFunction](https://github.com/tcz/phpunit-mockfunction)
- [PHPBuiltinMock](https://github.com/jadell/PHPBuiltinMock)
- [PHP-Mock](https://github.com/php-mock/php-mock) (it was not created at the time)
- [UOPZ](http://php.net/uopz)
- [runkit](http://php.net/runkit)

I finally started using UOPZ because I thought that more easy do use and it also allows you to overwrite the exit() language constructor.

**Comment by westtrade** [comment]
That's perfect! Thanks!
