### ISSUE TITLE
sha256 for releases on https://phar.phpunit.de/ ?

### ISSUE THREAD

**Issue by avindra** [sebastianbergmann/phpunit#1889]
Hi,

Currently, all the SHA1 sums are computed for phars on the distribution site. I've seen sha256 recommended over sha1, and it's fairly trivial to support it.

Is the code behind it open source? It would be nice to have a column added for sha256, so users such as myself don't have to compute the hash on our own.

Thanks.

**Comment by sebastianbergmann** [comment]
PHPUnit's PHAR distribution site (`https://phar.phpunit.de/`) is generated using https://github.com/sebastianbergmann/phar-site-generator

I already tried using SHA256 instead of SHA1 in the past (https://github.com/sebastianbergmann/phar-site-generator/commit/720b7ae0eb267523836cbc6318ad4e5d066996a0) but it broke the layout. Which, obiously, should not prevent us from using stronger cryptography.

**Comment by sebastianbergmann** [comment]
Moved to https://github.com/sebastianbergmann/phar-site-generator/issues/4
