### ISSUE TITLE
Implement --fail-on-risky and --fail-on-warning commandline options as well as failOnRisky and failOnWarning configuration options

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1905]
Use `exit(PHPUnit_TextUI_TestRunner::FAILURE_EXIT);` instead of `exit(PHPUnit_TextUI_TestRunner::SUCCESS_EXIT);` when there are no test failures and no test errors but risky tests or tests with warnings.

**Comment by rentalhost** [comment]
[The line 148](https://github.com/sebastianbergmann/phpunit/blob/4b94545180af80d03465b1099109394d0bfa1a10/src/TextUI/TestRunner.php#L148) broked phpunit because [`doRun() on line 89`](https://github.com/sebastianbergmann/phpunit/blob/4b94545180af80d03465b1099109394d0bfa1a10/src/TextUI/TestRunner.php#L89) will call it with only two arguments, and `$exit` argument is required. The fix is just append a `= false` on this.

**Comment by sebastianbergmann** [comment]
@rentalhost So that is what #2094 was about. Thanks!
