### ISSUE TITLE
Possible issue with type matching assertFalse()

### ISSUE THREAD

**Issue by chrisRidgers** [sebastianbergmann/phpunit#1923]
I've been attempting to use assertFalse and have been running into an issue where an empty string is returned as true, thus throwing an exception.

If you write test that calls:

```PHP
PHPUnit_Framework_Assert::assertFalse($string);
// Throws exception when $string is '' or '0'
```

var_dumping the boolean cast variable results in false,  and I've double checked using the interactive CLI.  I've also replaced my variable with a '0' and that too has failed to be asserted as false.

http://php.net/manual/en/language.types.boolean.php states that empty stings and strings of '0' should convert to false.

Is there some logic I've missed somewhere while digging or is this a bug?

**Comment by belanur** [comment]
PHPUnit's `isFalse` Constraint does a type safe comparison, so there is no implicit cast to boolean:
```
protected function matches($other)
{
    return $other === false;
}
``` 

So I would say the behaviour you described is intentional and that `assertTrue()` and `assertFalse()` should only be used for assertions on boolean variables.

If you already know that the variable you want to assert on contains a string, then you might want to do something like `assertEmpty()` or `assertSame('0', $string)` (again, this is a type safe comparison). 

If for whatever reason the type of the variable varies throughout the test (and that is most certainly a code smell), you could use `assertEquals(false, $string)` (not a type safe comparison, so the string will be cast to a boolean) or `assertFalse((bool)$string)` to get the behaviour you want.

**Comment by chrisRidgers** [comment]
That's fine if that's the intended behavior, I just wasn't  sure.

Cheers.
