### ISSUE TITLE
mapTestClassNameToCoveredClassName has no effect

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1936]

**Comment by hopeseekr** [comment]
What is the status of this ticket?

**Comment by sebastianbergmann** [comment]
This setting was removed long ago.

**Comment by hopeseekr** [comment]
I'm refactoring old code of mine, and I googled `mapTestClassNameToCoveredClassName` to try to figure out what it does. Lo, and behold, I find my own comment from 3 years ago. I still have no idea what it does or how to appropriately migrate my old app.

**Comment by SvenRtbg** [comment]
> 
> 
> I'm refactoring old code of mine, and I googled `mapTestClassNameToCoveredClassName` to try to figure out what it does. Lo, and behold, I find my own comment from 3 years ago. I still have no idea what it does or how to appropriately migrate my old app.

This feature once automatically assumed `@covers` annotations based on your test class name. If you had this feature enabled, and your test class is named `FooBarTest`, PHPUnit would automatically assume that everything inside this test will `@covers FooBar`. 

If you want to migrate anything, you'd either manually adding this annotation to the test class comment block (or any more fine-grained variants), or you could also disable the "covers" requirement so that every test automatically creates code coverage on every line that is being executed.
