### ISSUE TITLE
PHPUnit 4.6.0-4.8.x: Incorrect minimum PHP version in composer.json

### ISSUE THREAD

**Issue by tfrommen** [sebastianbergmann/phpunit#1989]
In PHPUnit versions 4.6.0 - 4.8.x, there is the dependency `"symfony/yaml": "~2.1|~3.0"`, and PHPUnit itself claims to require `"php": ">=5.3.3"`. Depending on which version of Symfony Yaml will be installed, however, this is not true. With version 2.7.0, Symfony Yaml requires `"php": ">=5.3.9"`, and with version 3.1.0 it is even `"php": ">=5.5.9"`.

To stick to PHP 5.3.3, the according require should thus be `"symfony/yaml": ">=2.1 <2.7"`. Or you leave it like it is, but change the required PHP version to 5.5.9 (in which case you could also just require `"symfony/yaml": "~3.0"` anyway).

**Comment by sebastianbergmann** [comment]
PHPUnit 4.6 and PHPUnit 4.7 are end-of-lifed and there will be no changes to them, much less new releases. PHPUnit 4.8 must be compatible with PHP 5.3, PHP 5.4, PHP 5.5, and PHP 5.6.

Not sure what to do here. Maybe @stof can advise?

**Comment by tfrommen** [comment]
Yes, I know the state of PHPUnit 4.6 and 4.7, I just tracked down where that require originated, and wanted to share what I found. :)

Thanks for the super-fast reply.

**Comment by stof** [comment]
*allowing* to install Yaml 3.0 does not make things incompatible with PHP 5.3. Composer will select the appropriate version based on your PHP version.

The case where an issue might happen is when dependencies are resolved on a different PHP version than the target one. But composer has a feature to cover this: you can tell it what the platform configuration is instead of making it read from the current platform (well, to be exact, you can overwrite some data, but this won't unset other extensions detected from the system): https://getcomposer.org/doc/06-config.md#platform

There is an example of such usage in Composer itself, to ensure that dependencies used in the composer phar stay compatible with PHP 5.3: https://github.com/composer/composer/blob/44bc8e019f8b4ac711b647b0693f84061ac7bb38/composer.json#L44

**Comment by GrahamCampbell** [comment]
https://github.com/composer/composer/blob/44bc8e019f8b4ac711b647b0693f84061ac7bb38/composer.json#L44

I'd totally recommend doing that. I do that in my applications so they work on the production environment.

**Comment by GrahamCampbell** [comment]
> allowing to install Yaml 3.0 does not make things incompatible with PHP 5.3. Composer will select the appropriate version based on your PHP version.

Totally correct. ;)

**Comment by sebastianbergmann** [comment]
Thank you, @stof. As far as I understand there is nothing for me to do here.

**Comment by stof** [comment]
@sebastianbergmann well, you need to ensure that the phpunit phar for 4.8 does not ship with Yaml 3.0 (as it would make the phar require PHP 5.5+). So the 4.8 branch should use this option in the composer.json to make sure the phar is shipped in the right way (and the 5.0 branch should do the same with PHP 5.6 to ensure it does not build with a dependency version requiring PHP 7)

**Comment by GrahamCampbell** [comment]
There you go: https://github.com/sebastianbergmann/phpunit/pull/1990.

**Comment by sebastianbergmann** [comment]
Thanks!
