### ISSUE TITLE
[4.8] JSON log output is not formatted correctly.

### ISSUE THREAD

**Issue by DaemonAlchemist** [sebastianbergmann/phpunit#2005]
The JSON log outputs objects appended directly to each other without being separated by commas.  The list of objects is also not wrapped with an array.  This results in an invalid JSON object which needs to be fixed by the consumer of the JSON before it can be parsed.

Expected
==========
```
[{...},{...},{...},...,{...}]
```

Actual
========
```
{...}{...}{...}...
```

**Comment by sebastianbergmann** [comment]
The JSON logger emits one valid JSON message per test executed. It's meant to be used in a streaming context.

**Comment by DaemonAlchemist** [comment]
Except that the --log-json option also allows streaming to a file.  That file then cannot be read directly as JSON, and must be fixed before it can be used.  It would be useful to have an option to emit a properly formatted JSON file that can be read asynchronously in a non-streaming context.

**Comment by sebastianbergmann** [comment]
Feel free to send a pull request that implements that.

**Comment by Jean85** [comment]
I would like to do this PR, but changing the output of `--log-json` would be a BC.
Should I wait `6.x` development to do it?

**Comment by jmauerhan** [comment]
Maybe a new flag like --log-json-to-file so the previous one could stay as is.

I need this too, would be happy to help.

**Comment by sebastianbergmann** [comment]
The original `--log-json` was added way back when a vendor asked for a stream of JSON messages to implement a progress bar in their IDE product. As far as I know, `--log-json` was never utilized for that.

Whether or not it was actually used, I see the point of using JSON for "streamed logging". For "non-streamed logging", however, I have to admit that it eludes me why JSON would be prefered over JUnit XML.

To be honest, I would rather remove the JSON logger (as well as the TAP logger, while we're at it) instead of changing it. If people really want this then they are free to provide the functionality in a separate package (and register the logger in PHPUnit's XML configuration file using `<listener>`).

**Comment by Jean85** [comment]
I'm using the JSON logger for better performances and faster output in my package, Paraunit. It runs PHPUnit tests in parallel, so performance are an issue.

That's  why I preferred it over XML.

**Comment by jmauerhan** [comment]
I use the json logger as well, it was easier to parse the results I wanted from JSON than any other format - except for the fact that it was invalid json, so I had to manipulate it first :) 

If I started a new repo for the logger with the correctly formatted output (for non stream use), would anyone else here be interested in contributing? I'd love to do that!

**Comment by Jean85** [comment]
I would like to contribute, but I'm not sure about how much time I could dedicate to that.

Also, I'm not sure about how an external lib could do all of this! Right now, we're requesting this specific output with a CLI option; how could we request the same thing without a huge BC break?

And how we could do it without having to edit the PHPUnit XML config? Right now my project (https://github.com/facile-it/paraunit) uses the JSON log and requests it through the CLI, so it works out-of-the-box, without having to modify the XML... I would love the leave it like that, if possible.

**Comment by jmauerhan** [comment]
As @sebastianbergmann said, it's possible to "register the logger in PHPUnit's XML configuration file using <listener>"

**Comment by Jean85** [comment]
Yeah, I understood that. But I'm running PHPUnit in separate processes (the goal is to run tests in parallel), so registering something in that way will not work for me, because I will have no (easy) way to communicate from my Paraunit process to the PHPUnits... 

For example, to enable a naming strategy for the JSON log files, to make matching easier between my process and the single test and its log. Or I missing something?

**Comment by jmauerhan** [comment]
Sorry, I completely missed that part :) Maybe you'd be better off using the streaming log instead of a file?

**Comment by Jean85** [comment]
Currently, I'm using that, without the streaming part... I'm editing it too, because it would get too complicated to decode that as a stream, and also to detect when a stream is completed.

Anyhow, thanks for listening to my rants :D I will gladly lend a hand if I can..
