### ISSUE TITLE
Testsuite with name="directory" causing fatal error

### ISSUE THREAD

**Issue by redaxmedia** [sebastianbergmann/phpunit#2013]
Hello Sebastian,

please rename PHPUnit's internal **small** testsuite to **directory** to reproduce following error:

<pre>
henry:~/Projekte/phpunit$ php phpunit.phar --configuration phpunit.xml --testsuite directory
PHP Fatal error:  Uncaught PHPUnit_Framework_Exception: Class "Directory" does not extend PHPUnit_Framework_TestCase.

phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/Framework/TestSuite.php:167
phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/Util/Configuration.php:823
phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/Util/Configuration.php:804
phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/TextUI/Command.php:663
phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/TextUI/Command.php:117
phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/TextUI/Command.php:106

  thrown in phar:///home/henry/Projekte/phpunit/phpunit.phar/phpunit/Framework/TestSuite.php on line 167</pre>

Can you confirm this is a valid error? Tested with latest version of PHPUnit.

**Comment by sebastianbergmann** [comment]
Can you provide a minimal, reproducing example?

**Comment by redaxmedia** [comment]
Just rename PHPUnit's internal testsuite **small** testsuite to **directory**:

<pre>
&lt;testsuite name=&quot;directory&quot;&gt;
  &lt;directory suffix=&quot;Test.php&quot;&gt;tests/Framework&lt;/directory&gt;
  &lt;directory suffix=&quot;Test.php&quot;&gt;tests/Extensions&lt;/directory&gt;
  &lt;directory suffix=&quot;Test.php&quot;&gt;tests/Runner&lt;/directory&gt;
   &lt;directory suffix=&quot;Test.php&quot;&gt;tests/Util&lt;/directory&gt;
&lt;/testsuite&gt;
</pre>

**Comment by original-brownbear** [comment]
Added PR #2022 

I don't think this should be fixed, only documented. If I understand the existing test cases for this constructor correctly it is expected behavior to throw an exception in case the test suit name collides with an existing class that is not a subclass of PHPUnit_Framework_TestCase.
I don't see how the use of the name of a PHP core [class](http://php.net/manual/en/class.directory.php)
would be any different here?

=> Added a test documenting this behavior in the PR.
