### ISSUE TITLE
Can't test that a given mock should be returned

### ISSUE THREAD

**Issue by danizord** [sebastianbergmann/phpunit#2042]
Since https://github.com/sebastianbergmann/phpunit/issues/1902 I can't do the following test anymore:
```php
$something = new Something();
$stuff     = $this->prophesize(Stuff::class)->reveal();
        
$something->setStuff($stuff);
        
$this->assertSame($stuff, $something->getStuff());
```

That throws `PHPUnit_Framework_RiskyTestError` "This test performed an assertion on a test double"

**Comment by tim-bezhashvyly** [comment]
I'm afraid it is a bug.

**Comment by sebastianbergmann** [comment]
Here is a complete reproducing test case:
```php
<?php
class A
{
    private $b;

    public function setB(B $b)
    {
        $this->b = $b;
    }

    public function getB()
    {
        return $this->b;
    }
}

class B
{
}

class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $b = $this->getMock(B::class);
        
        $a = new A;
        $a->setB($b);

        $this->assertSame($b, $a->getB());
    }
}
```
Not sure what to do here. Maybe @spriebsch has an idea?

**Comment by spriebsch** [comment]
Is this "running an assertion on a mock"? It's comparing a mock with something else, which has to be "allowed".

While I do not remember the original train of thought that made me open #1902 (shame on me!), I realize today that my wording was unclear (shame on me again). I *think* there is a difference between having an assertion call a method in a mock (as in: getFoo(), which returns null, because the mock is not configured to return anything, and you start to debug your production code because you are not realizing that the assertion operates on a mock) and passing around a mock and using it as an argument of an assertion (at least for comparison, this must be "allowed", as the above test cases prove). 

Lessons learned: I'll be much more verbose in my tickets in the future, because I'm realizing that a few months later, I just don't know what I was thinking when I wrote the ticket.

Sorry about any trouble that my inaccuracy may have caused. I think what should be done next is to understand which different cases (I mentioned two above, there may be more) there are, and how to deal with each one. @sebastianbergmann, give me a call if you want to discuss this.

**Comment by sebastianbergmann** [comment]
Thank you for the clarification, @spriebsch, I was thinking the same. However, I have no idea right now how to differentiate the situations you describe in the code that implements this feature. I might have to remove the feature, at least for now.

**Comment by localheinz** [comment]
@sebastianbergmann 

Noticed the same thing as pointed out in https://github.com/sebastianbergmann/phpunit/issues/2042#issuecomment-180747186. 

Any idea if this will be resolved, or shall we just start not mocking dependencies anymore? 🤓

**Comment by sebastianbergmann** [comment]
The implementation of #1902 has been removed.
