### ISSUE TITLE
getMock didn't throw error when class not found

### ISSUE THREAD

**Issue by gimler** [sebastianbergmann/phpunit#2073]
When i try to get a mock for a class and forget to load the class in my test i didn't get a error ;(

```
<?php

class MockTest extends \PHPUnit_Framework_TestCase
{
    public function testMock()
    {
        $mock = $this->getMockBuilder('\classNotExist')->disableOriginalConstructor()->getMock();

        var_dump($mock);
    }
}
```

**Comment by sebastianbergmann** [comment]
* This is expected behaviour
* Your IDE and PHP can help you with this when you use `getMockBuilder(Type::class)` instead of `getMockBuilder("Type")`
* This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project
