### ISSUE TITLE
Self update error

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#2107]
I'm encountering the same problem as stated in this old issue (#1688) on Travis for a PHP 5.6 build: [build link](https://travis-ci.org/theofidry/LaravelYaml/jobs/114059727).

The PHPUnit version is the Travis default one: 4.5.0.

Error stack trace:

```
$ phpunit --self-update
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.
Updating the PHPUnit PHAR ... PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php on line 843
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:114
PHP   5. PHPUnit_TextUI_Command->handleSelfUpdate() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:521
PHP   6. file_get_contents() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:843
```

**Comment by sebastianbergmann** [comment]
The PHAR of PHPUnit releases prior to PHPUnit 4.6.5 (see https://github.com/sebastianbergmann/phpunit/issues/1688#issuecomment-103718180) contain an SSL certificate that does not match the one in use on `phar.phpunit.de` today.

This is not a bug. It cannot be fixed. The best way to deal with the issue at hand would be to either download `https://phar.phpunit.de/phpunit.phar` directly instead of using `phpunit --self-update` or, even better, put the `phpunit.phar` in your project's sourcecode repository.

**Comment by theofidry** [comment]
Yeah but the point of using Travis default PHPUnit phar si to avoid having a PHPUnit 5.x for example on a PHP 5.3 or 5.4 build (which is not supported).

But I guess I should open a ticket on Travis repo for it. Thanks.
