### ISSUE TITLE
assertNotContains fails if array contains boolean (Regression - Version 5.2.10)

### ISSUE THREAD

**Issue by mhousser** [sebastianbergmann/phpunit#2111]
Simple test case:

``` php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testBug()
    {
        $array = ['foo' => 'string'];
        $this->assertNotContains('nope', $array);

        $array['bar1'] = 'another string';
        $this->assertNotContains('nope', $array);

        $array['bar2'] = true;
        $this->assertNotContains('nope', $array);
    }
}
```

As of 5.2.10, the final assertion `$this->assertNotContains('nope', $array);` is failing. The moment there's a `boolean` (and perhaps other primitive types? haven't tested around) in the array, the `needle` is somehow magically found, even though it's most certainly _not_ supposed to be found.

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is also affected.

**Comment by sebastianbergmann** [comment]
In https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/Constraint/TraversableContains.php#L86 `true == 'nope'` is performed and evaluates to `true`. That is, of course, correct (according to PHP's type system) but not what we want here.

`assertContains()` and `assertNotContains()` have an optional argument `$checkForNonObjectIdentity` that defaults to `false`. When this set to `true` then the `===` operator would be used instead of `==`.

Maybe we need special treatment for `true` and `false` as needles as well as `true` as an element of the haystack.

**Comment by v** [comment]
This issue also affects `assertContains` (unsurpisingly)

```
<?php

use PHPUnit\Framework\TestCase;

class ContainsTest extends TestCase
{
    public function testContains()
    {
        $this->assertContains('foo', [true]);
    }
}
```

This test passes, when it probably shouldn't

**Comment by KrunoKnego** [comment]
As @sebastianbergmann already pointed out, this issue is occurring because ```$checkForNonObjectIdentity``` is not set to true. 

Without that parameter set to true, the non-objects are going to be loose-compared. In your case you have a string ```nope``` and a boolean variable ```true```, if you refer to http://php.net/manual/en/types.comparisons.php#types.comparisions-loose this is supposed to give you true which is what the code does and gives you back the error message which can be translated into "string ```nope``` is part of your haystack".

Now on to explain why this is working like this. PHPUnit gives you ability to test both clean and the proverbial "smelly code". People should be able to cover both types of code and later on through refactoring come up with the clean code.
