### ISSUE TITLE
assertObjectHasAttribute is rejecting number only attributes 

### ISSUE THREAD

**Issue by oliworx** [sebastianbergmann/phpunit#2168]
testing a REST-Api I have a JSON object with attributes like "00001" .
In the test this is converted to a PHP-Object.

```
$data = json_decode($response->getContent());
$this->assertObjectHasAttribute('00001', $data );
```

and I get
`PHPUnit_Framework_Exception: Argument #1 (No Value) of PHPUnit_Framework_Assert::assertObjectHasAttribute() must be a valid attribute name`

This is probably due to the regexp pattern:
`if (!preg_match('/[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*/', $attributeName))`

**Comment by akeeman** [comment]
I just came across a similar case, where I unfortunately have formatted dates as keys (i.e. '2016-05-18').
I'm sure it's because of the that regex, because tests point out changing this regex fixes the behavior. Therefore I suggest to add 0-9 to valid start characters and add a dash to valid follow-up characters.

However, I do not write a pull request yet as I expect someone made this specific regex, leaving out these characters, with a reason. So does anyone have any thoughts about this? If not, I'll be happy to submit a pull request in the coming days...

**Comment by sebastianbergmann** [comment]
`/[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*/` describes strings that are valid attribute names in PHP. It comes from PHP's compiler. If you somehow create objects that have invalid attribute names, for instance by using `json_decode()`, then, I am sorry, you cannot use `assertObjectHasAttribute()` to test these objects.
