### ISSUE TITLE
Phpunit stop during tests after adding second condition to if

### ISSUE THREAD

**Issue by Jerome1337** [sebastianbergmann/phpunit#2171]
I have a symfony command test file with a two conditions `if` on it 

```
if (empty($invalidSshkey) || empty($domains)) {
    $this->io->success('No outdated SSH keys found.');
    exit(1);
}
```
Before I add `empty($domains)` phpunit didn't fail on this test and was working well. `$domains` is a simple array

When I start Phpunit, it's working normally but when phpunit test this file, it stop without showing any errors. I tried to use phpunit with `--verbose` or/and `--debug` without success.

The only thing it show is a `%` before stopping

![selection_037](https://cloud.githubusercontent.com/assets/7968649/15429552/bab46cfe-1ea1-11e6-873e-99fde43b1414.png)

I'm working with 
* Ubuntu `15.10` 
* PHP `5.6.11` 
* Phpunit `5.2.9` 
* Xdebug `2.3.3` 

This weird problem is only made in local. On distant server phpunit working well.

**Comment by jmauerhan** [comment]
Can you clarify, is the exit statement in a test, or a file you are trying to test? 

Did you confirm that the other server you tested it on is using the same versions of php/phpunit etc

**Comment by Jerome1337** [comment]
The exit statement is in the file I am trying to test.

The other server is running version `5.3.4` of phpunit, it's maybe related to this problem

**Comment by jmauerhan** [comment]
So, it sounds like the logic of the file when you're testing it means that `empty($invalidSshkey) || empty($domains)` is evaluating to true, and then the exit statement is running. 

Try adding the `@runInSeparateProcess` tag on that test, so that PHP unit is not affected by the `exit()`. 

You could also use something like AspectMock: https://github.com/Codeception/AspectMock or PHP-Mock: https://github.com/php-mock/php-mock to create a double of the `exit` statement if you need to test that it is called.

**Comment by Jerome1337** [comment]
Thanks for your help, `@runInSeparateProcess` fix this problem.
I keep AspectMock and PHP-Mock in my mind too. :)
