### ISSUE TITLE
Xdebug is not entering the unit test after PHPUnit_TextUI_Command::main();

### ISSUE THREAD

**Issue by jepster** [sebastianbergmann/phpunit#2245]
I'm using PHPUnit for tests within Drupal 8. Also I'm using Xdebug for all my other tasks. However if I want to use Xdebug to debug my PHPUnit test, then the debugger is not entering my unit test. 

Immediately after 

PHPUnit_TextUI_Command::main();

was executed from the test runner script, the execution seems to "hang". If I click on the green phone icon in the PhpStorm ide to switch debugging off, the test continues. It could be that the breakpoint is hit but my PhpStorm ide does not recognize it. The terminal output displays the following: 

![terminal](http://storage2.static.itmages.com/i/16/0715/h_1468595626_5702490_1017af969c.png)

My debug window in the PhpStorm ide displays the following:

![debug window](http://storage4.static.itmages.com/i/16/0715/h_1468596177_3360804_b7adc37bd6.png)

The environment variable was set by:

PHP_IDE_CONFIG="serverName=pbt-d8"

It didn't help. Without debugging enabled in PhpStorm via the green phone symbol, the test is being executed. Is there any separated process? But "--process-isolation" is not being used. Also the simultaneous connections in PhpStorm are set to 3.

I have read that debugging unit tests with xdebug is possible. Could you please give me a hint about how I can fix my issue?

**Comment by sebastianbergmann** [comment]
Sorry, but I am unable to help.

I use PhpStorm as my IDE but I do not execute my tests with it. I use Xdebug but I do not use it for debugging.

Maybe @derickr or @SvetlanaZem can help?

**Comment by derickr** [comment]
It's probably best to try to make a remote debugging log as well (see https://xdebug.org/support.php#remote).

**Comment by SvetlanaZem** [comment]
@jepster Have you tried to execute tests from IDE instead of command line? Debugging will be available by one button then without 'PHP_IDE_CONFIG' or green phone symbol.

You can setup PHPUnit integration in `'Settings|PHP|Test Frameworks'`
1) Add local configuration for PHPUnit; 
2) Select 'Use Composer autoloader' and set '/path/to/projevt/vendor/autoload.php'. 

To execute tests invoke context menu from a test file and select `Run 'MyFileTest'` (or use shortcut 'Ctr+Shift+F10').

**Comment by sebastianbergmann** [comment]
No feedback, closing.
