### ISSUE TITLE
Passing an integer to the message argument of setExpectedException causes the message matching to always pass

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#2267]
> PHPUnit 4.8.26

``` php
public function testInteger() {
    $this->setExpectedException(Exception::class, 1);

    throw new Exception('2'); // Pass
}

public function testString() {
    $this->setExpectedException(Exception::class, '1');

    throw new Exception('2'); // Failed asserting that exception message '2' contains '1'.
}
```

I believe the message argument should automatically be typecast to string.

**Comment by stevenbitner** [comment]
In PHPUnit 5.4 passing other than a string value for the message will give you the following failure:
`PHPUnit_Framework_Exception: Argument #1 (No Value) of PHPUnit_Framework_TestCase::expectExceptionMessage() must be a string`

**Comment by leedwilkins** [comment]
setExpectedException has been decripcated, in checking expectExceptionCode, expecteExceptionMessage, and expectExceptedMessageRegex I realized that the tests are not run if the string is empty. It was originally using the empty() method, which meant that '0' would also be skipped. I changed it so that only the empty string is skipped, but technically even that should be checked. The problem is that, if it tries to test and empty string many errors/failures occur. This will take some more looking into.
