### ISSUE TITLE
Exclude tests from package distribution

### ISSUE THREAD

**Issue by neomerx** [sebastianbergmann/phpunit#2300]
Currently if phpunit is installed as a project dependency, composer downloads it with tests and some other not necessary files. And some of the phpunit names get IDE code helpers messy

![image](https://cloud.githubusercontent.com/assets/10420662/18758392/942bcdea-8100-11e6-8f84-f302c7d61009.png)

The solution is to instruct git/composer to ignore some of the files and folders by adding to `.gitattributes` a list of files/folders

```
/tests              export-ignore
/.gitattributes     export-ignore
/.gitignore         export-ignore
/.php_cs            export-ignore
/.travis.yml        export-ignore
...
```

**Comment by alcohol** [comment]
This does break anyone installing phpunit from github zipballs and attempting to install the dependencies, because of the explicit classmap reference in `autoload-dev` to the `tests` directory. Possible solutions here would be to switch to using PSR-0/PSR-4 instead of classmap (if this is something that you would want to address).

**Comment by sebastianbergmann** [comment]
@alcohol If you think that this breaks something that should not be broken then please open a new ticket.
