### ISSUE TITLE
ResultPrinter produces inconsistent output if TestCase produces (unexpected) output

### ISSUE THREAD

**Issue by Robotic-Brain** [sebastianbergmann/phpunit#2321]
What is the expected behavior if you have a test case like this?

``` PHP
class SomeTest extends PHPUnit_Framework_TestCase
{
    public function testPrintStringFoo()
    {
        print 'foo';
    }
}
```

According to several answers on SO [[1]](http://stackoverflow.com/a/8791103/5343341) [[2]](http://stackoverflow.com/a/8076529/5343341) (I couldn't find an "official" source) phpunit should print the test output directly after the progress character like this:

```
PHPUnit 5.6.0 by Sebastian Bergmann and contributors.

.foo                                                                1 / 1 (100%)
```

However, I just ran into this while debugging an unrelated problem:

``` PHP
class SomeTest extends PHPUnit_Framework_TestCase {
    public function testPrintStringFoo() {
        print 'foo';
    }
    public function testPrintStringBar() {
        print 'bar';
    }
}
```

Prints this: (notice the `bar` at the end)

```
PHPUnit 5.6.0 by Sebastian Bergmann and contributors.

.foo.                                                                  2 / 2 (100%)bar
```

adding a 3rd test case: 

``` PHP
// ...
    public function testEmpty() {
        // workaround
    }
```

Prints this:

```
PHPUnit 5.6.0 by Sebastian Bergmann and contributors.

.foo.bar.                                                              3 / 3 (100%)
```

Obviously there is a "bug" if the last test case returns some output to `stdout`. But since I couldn't find any documentation on it, it makes me wonder if this type of `printf() debugging` is actually supported by phpunit?

**Comment by vbashkirtsev** [comment]
A lot of people use PHPUnit tests for debugging and throw in echo and print statements. However PHPUnit is not a debugging tool and it never was - it is testing framework, Nothing more, nothing less. Attempt to use it for debugging like you have demonstrated is entirely your responsibility and PHPUnit is not responsible for nice layout of spurious messages from tests.

For example if you put @runTestsInSeparateProcesses in your test class and then try to echo/print something will cause an error with unserialization in PHPUnit. Should we blame PHPUnit? No, Because it was not designed for this.

So there no "bug" in the way how PHPUnit handles last test case: the "bug" is in the use of "print" in test iteself.

Don't want to sound rude but here the old joke: student programmer comes to his mentor with code listing and asks "It does not work! Can you please tell me where the bug is?" Mentor looks up and says "In your DNA!" :)

While you may continue to use PHPUnit test cases for debug purposes with echo/print statements I would recommend to use $this->fail and assertions instead. This way you invoke PHPUnit's ways to deal with failures/errors and they will be shown in the clean and nice way.

For example to "print" an array you can do:

$arraytoprint = array("a", "b", "c");
$this->assertEquals(array(), $arraytoprint);

**Comment by Robotic-Brain** [comment]
So is printing in tests officially "undefined behavior"?
I was wondering because printf debugging seems to be common practice in PHP.
(Even though it's considered bad style in compiled languages)

If it is really a bug, i have a patch almost ready. Otherwise this can be closed.

**Comment by vbashkirtsev** [comment]
The only "official" output in PHPUnit is what is done with PHPUnit methods (asserts and fail()). AFAIK there no specific output methods for debugging.

I guess printf debugging is common practice but PHPUnit cannot be made responsible for whatever output generated by tests/code. So it is responsibility of the user to prettify such sort of output.

In the same time there no harm of making a PR which makes PHPUnit a bit more friendlier to such output - I personally don't see any problem with that.

**Comment by vbashkirtsev** [comment]
Just a side thought: in our team we actually use PHPUnit extensions. In the end PHPUnit's test case is just a class and therefore it may be extended. We extend it with features which we need but which will not make sense in mainstream PHPUnit (otherwise we would push it here). This should allow you easily to make extended test case class which may have printf() method and then you can use it in your own tests.

**Comment by Robotic-Brain** [comment]
This doesn't really solve the problem...
In my example above, the TestCase directly prints something.
But the actual use case is, if the SUT (System Under Test) is printing some debug information.
And the SUT should never depend on anything from the test harness.
Obviously the "correct" way would be to use a custom Logger implementation, that bridges the output to phpunit and is injected during some boot process before each test.

Anyways it's just a quirk I noticed, and wanted to get fixed...

**Comment by vbashkirtsev** [comment]
In your original post you have used "print" in the test itself: naturally we should have no problem of implementing extra methods through class extension to handle output in the tests. But it should work for SUT in the similar way. As it stands now PHPUnit captures all the output and you can assert against it if you want. But because PHPUnit is not a debugger it was never meant to output captured SUT output in any meaningful way.

Again: you can extend TestCase class and override what PHPUnit does to captured output. This way SUT will remain as-is and totally unaware that its output is captured and redirected as you please. But I doubt that it is something mainline PHPUnit should handle.

And again: I don't see any harm in sending in a PR addressing this issue and see if it will be accepted.

In our own setup we have a class which extends from TestCase which not only handling SUT output but also intercepts exit() in SUT so PHPUnit continues tests execution even if SUT dies unexpectedly. And this does not require any change in PHPUnit.
