### ISSUE TITLE
No way to require PHP 7.0 only (not a later version) using an annotation

### ISSUE THREAD

**Issue by ondrejmirtes** [sebastianbergmann/phpunit#2386]
Hello,
there's no way to require a test to run on PHP 7.0 and not on PHP 7.1 if I have a test that tests specifically a situation that makes sense only on PHP 7.0. The @requires annotation means "this version and all later versions" so I have to use a custom if condition with markTestSkipped.

**Comment by dnaber-de** [comment]
So a possible solution would be to use version constraints (like for example used by Composer). In that case that would be:

```PHP
/**
 * @requires PHP ~7.0
 */
public function testRunsOnlyOn70 { /*… */ }
```

In order to maintain BC `@requires PHP 5.6.3` must still be interpreted as `@requires PHP <=5.6.3` for example. https://github.com/phar-io/version can be used for parsing the version constraints as it will be a dependency as of PHPUnit 6.1 anyway.

**Comment by sebastianbergmann** [comment]
Re: https://github.com/sebastianbergmann/phpunit/issues/2386#issuecomment-290659708

I think you mean `@requires PHP >= 5.6.3` instead of `@requires PHP <= 5.6.3`.

**Comment by dnaber-de** [comment]
Of course, thanks. Fixed the typo.
