### ISSUE TITLE
Test without assertions executed in process isolation does not get marked as risky

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2574]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | `^5.7 || ^6.0`
| PHP version         | 7.1.3
| Installation Method | Composer

```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    /**
     * @runInSeparateProcess
     */
    public function testOne()
    {
        exit;
    }
}
```
```
$ phpunit Test
PHPUnit 6.0.9 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 68 ms, Memory: 4.00MB

OK (1 test, 0 assertions)
```
```
$ phpunit --report-useless-tests Test
PHPUnit 5.7.16 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 102 ms, Memory: 4.00MB

OK (1 test, 0 assertions)
```

**Comment by mcustiel** [comment]
Just to add information: This was closed because it was behaving as expected. 
As the isolated process exited inside the script, there were no way for PHPUnit to know what happened since all checks are done after the test method finishes. If the exit() function is not called, then the test is marked as Risky correctly because it continues executing.
