### ISSUE TITLE
setUp and setUpBeforeClass run before filters/groups applied

### ISSUE THREAD

**Issue by banks** [sebastianbergmann/phpunit#261]
I'm not sure if this is intentional but I don't see the rationale if it is. I also couldn't find documentation or other issues to suggest this is a known/discussed topic.

Basically: I user the `filter` and/or `groups` options to limit the tests run by the test runner as documented.

I've realised though that since the code that calls `setUp()` and `setUpBeforeClass()` methods is _before_ the filtering is applied, ([code link](https://github.com/sebastianbergmann/phpunit/blob/3.5/PHPUnit/Framework/TestSuite.php#L653)) every test in my suite will have `setUp()` run and every test case will have `setUpBeforeClass()`. This means any expensive setup work done is run for the whole suite even when the tests that require the work are not being run.

I'm aware that you can specify specific test case classes to run and thus avoid this but in a very large test suite, the flexibility of `filter` and `groups` is very useful. It comes with a huge cost of running potentially thousands of setup routines though just to run a single simple test.

If this is intentional behaviour, it would be great to understand the rationale behind it. If not, it appears a relatively simple fix and I am can fork and make the required changes.

Thanks for you time and effort on this PHPUnit!

**Comment by redgeoff** [comment]
Here is a post on SO that may help others who are still having problems with the filtering not preventing the fixtures from being run: [PHPUnit filtering not working with setUpBeforeClass() and tearDownAfterClass()](http://stackoverflow.com/questions/33511053/phpunit-filtering-not-working-with-setupbeforeclass-and-teardownafterclass/33511054#33511054)

I'm sorry if there is a better way that I have just missed in the docs.
