### ISSUE TITLE
Expected error with self::once()

### ISSUE THREAD

**Issue by north69** [sebastianbergmann/phpunit#2667]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.0
| PHP version         | 7.1.0
| Installation Method | Composer / PHAR

Hello, I have a problem with an expectation the method call. I expect error if the method isn`t called, but test finished OK. Example here.

```
class EchoClass {

	public function methodForMocking() {
		echo 'hello';
	}

	public function echoMethod() {
		return true;
	}
}

class EchoClassTest extends TestCase {
       
       /**
        * methodForMocking isn`t called but there is not error
        */
       public function testEcho() {
		/** @var EchoClass|\PHPUnit_Framework_MockObject_MockObject $mock */
		$mock = $this->getMock(EchoClass::class, ['methodForMocking']);
		$mock->expects(self::once())->method('methodForMocking')->will(self::returnValue(true));
		$result = $mock->echoMethod();
		$this->assertSame(true, $result);
	}
}
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by north69** [comment]
I`ve copied to https://github.com/sebastianbergmann/phpunit-mock-objects/issues/360
