### ISSUE TITLE
Coverage: accolades and brackets not covered

### ISSUE THREAD

**Issue by stephanvierkant** [sebastianbergmann/phpunit#2701]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.1
| PHP version         | 7.1.5
| Installation Method | Composer

As of 6.2, lines with only accolades, brackets or semicolons are not marked as covered. Problem didn't occur on 6.1 and 6.0.

![Screenshot PhpStorm](http://i.imgur.com/vXG7kKf.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
