### ISSUE TITLE
Wrong code coverage if method arguments are split across multiple lines

### ISSUE THREAD

**Issue by markwatney2016** [sebastianbergmann/phpunit#2727]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.3
| PHP version         | 7.0.17
| Installation Method | Composer

Please compare the attached screenshots of the code coverage report.

All method arguments on one line:

![code-coverage-one-line](https://user-images.githubusercontent.com/22563689/27830116-35e2004c-60c5-11e7-9801-22efe9d07adf.png)

Method arguments split across multiple lines:

![code-coverage-multi-line](https://user-images.githubusercontent.com/22563689/27830117-35e3f21c-60c5-11e7-9406-8668b47237f2.png)

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project. Please open a new ticket there that contains the information listed above.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
