### ISSUE TITLE
HTML Code coverage highlighter broken since 6.2.2

### ISSUE THREAD

**Issue by illusive-man** [sebastianbergmann/phpunit#2730]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.2-6.2.3
| PHP version         | 7.1.2
| Installation Method | Composer 

Highlighted lines are shown wrong. I would say - one line lower from the one it should highlight actually. 
BTW, code coverage for this class is 100%.

See the screenshot. 

![2017-07-06_2-16-43](https://user-images.githubusercontent.com/25516639/27888884-4bec3f10-61f1-11e7-8f93-a0e8c1f190eb.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by illusive-man** [comment]
Got it. I will report it there.
