### ISSUE TITLE
Full list of Assertions

### ISSUE THREAD

**Issue by playmono** [sebastianbergmann/phpunit#2752]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.3
| PHP version         | 7.1.6-2
| Installation Method | Composer

Where can I see a full list of Assertions? I recently noticed there is an "assertJson" (just randomly typed and worked) and it's not listed here: https://phpunit.de/manual/current/en/index.html

Is that website outdated? Or I am missing something?

Thanks.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
