### ISSUE TITLE
Confusing example of test suites XML configuration

### ISSUE THREAD

**Issue by jtreurniet** [sebastianbergmann/phpunit#2755]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.0
| PHP version         | 7.1.7
| Installation Method | PHAR

In appendix C of the manual, covering the XML configuration file (https://phpunit.de/manual/current/en/appendixes.configuration.html), the example provided for test suites shows the following line:

`<directory>/path/to/*Test.php files</directory>`

In exploring the wondrous world of XML configuration files for the first time, I wrote

`<directory>/my/actual/path/to/*Test.php</directory>`

When attempting to run phpunit, it was not recognizing the test that I had placed in the directory. Removing the `*Test.php` from the specified path resolved this. Assuming that wildcard notations like that are indeed not allowed, it seems to me like the example is slightly confusing, and should instead contain something like

`<directory>/path/to/tests/directory</directory>`

making it clear that the `*Test.php` part is neither necessary nor supported.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
