### ISSUE TITLE
"logIncompleteSkipped" option is missing since version 6.0

### ISSUE THREAD

**Issue by more7dev** [sebastianbergmann/phpunit#2779]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.x
| PHP version         | 7.1
| Installation Method | Composer

In [current manual](https://phpunit.de/manual/current/en/appendixes.configuration.html) there is an option described, named "logIncompleteSkipped".

Prior to version 6.0 it was present in [Configuration.php](https://github.com/sebastianbergmann/phpunit/blob/5.7.21/src/Util/Configuration.php) file.
Since 6.0 it disappeared from Configuration.php and setting this option has no effect on jUnit output xml.

configuration.xml: 
> 
    <logging>
        <log type="junit" target="junit.xml" logIncompleteSkipped="false" />
    </logging>

junit.xml - information about skipped tests is still present: 
> 
    <testcase name="example" class="Example" classname="Example" file="Example.php" line="48" assertions="0" time="0.688695">
        <skipped/>
    </testcase>`

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by more7dev** [comment]
I didn`t know if this option had been intentionally removed or it is just a bug. 
In the [changelog](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md) there is no mention about removal.

It is a pity that you decided to remove it. In my opinion it is sometimes useful, in my case for example, Jenkins [has problem with parsing](https://issues.jenkins-ci.org/browse/JENKINS-42715) `<skipped/>` tag and removing it from output would solve the problem until Jenkins has this issue fixed. Without this option, resolution will be a bit more complicated.

**Comment by sebastianbergmann** [comment]
The ChangeLog reads "The logfile format generated using the --log-junit option and the <log type="junit" target="..."/> configuration directive has been updated to match the current format used by JUnit. Due to this change you may need to update how your continuous integration server processes test result logfiles generated by PHPUnit."

**Comment by aistis-** [comment]
Ran into the same problem. @more7dev did you manage to find a workaround for it?

**Comment by more7dev** [comment]
My workaround is to remove <skipped/> tags from generated junit.xml, so that Jenkins can successfully parse them. 

I do it in my CI script, after running phpunit:
`sed -i -e 's/<skipped\/>//g' "junit.xml"`

I see corresponding [Jenkins issue](https://issues.jenkins-ci.org/browse/JENKINS-42715) still not fixed...

**Comment by aistis-** [comment]
@more7dev worked great 👍 

However, now junit handler seems working! Just replace phpunit handler by junit handler.

![example](https://www.evernote.com/l/ADAIw0MQuONISq0_Cz0ECGDWbhBFxUzyRaMB/image.png)
