### ISSUE TITLE
Coverage in phpunit 6

### ISSUE THREAD

**Issue by piernik** [sebastianbergmann/phpunit#2797]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.1
| PHP version         | 7.0
| Installation Method | Composer

I'm trying to get code coverage in phpunit 6. I know I have to add config to phpunit.xml file but it still not works.

I have two folders - in tests I have tests and in src I have my source files.

My phpunit config file:

```
<phpunit bootstrap="vendor/autoload.php">
    <testsuites>
        <testsuite name="SlimSkeleton">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">tests</directory>
        </whitelist>
    </filter>
</phpunit>
```
With that configuration I get code coverage only in tests folder - not in src:/

When I change config file to:

```
<filter>
    <whitelist processUncoveredFilesFromWhitelist="true">
        <directory suffix=".php">tests</directory>
        <directory suffix=".php">src</directory>
    </whitelist>
</filter>
```
I get php errors like PHP Fatal error:  Uncaught Error: Call to a member function getContainer() on null in ...

None of those errors occur when running tests without coverage.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

That being said, you must not put the `tests` directory onto the whitelist. You are only interested in code coverage for the sourcecode files in your `src` directory.

Fatal errors such as the one you are getting imply that there are sourcecode files in your `src` directory that contain code outside the scope of classes or functions that gets executed upon loading. Either exclude those sourcecode files from the whitelist or disable `processUncoveredFilesFromWhitelist`.

**Comment by piernik** [comment]
Many thanks. Switching flag `processUncoveredFilesFromWhitelist` to  `false` resolved my issue.
