### ISSUE TITLE
6.4 Docs are out of date with regard to --report-useless-tests

### ISSUE THREAD

**Issue by tentus** [sebastianbergmann/phpunit#2827]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.0.24
| Installation Method | Composer

The docs at https://phpunit.de/manual/current/en/risky-tests.html reference the --report-useless-tests option, but a look at the source code indicates this has been switched out for --dont-report-useless-tests

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
