### ISSUE TITLE
Mocking class that contains a method with 'iterable' return type

### ISSUE THREAD

**Issue by andaniel05** [sebastianbergmann/phpunit#2837]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.1.1
| Installation Method | PHAR

PHP Fatal error:  Cannot use 'iterable' as class name as it is reserved in phar://xxxxxxxx/phpunit-6.4.3.phar/phpunit-mock-objects/Generator.php(263) : eval()'d code on line 1

```php
<?php

use PHPUnit\Framework\TestCase;

class Foo
{
    public function traverse(): iterable
    {
        $gen = function () {
            yield 1;
            yield 2;
            return 3;
        };

        return $gen();
    }
}

class Bar
{
    public function run(Foo $foo)
    {
        $foo->traverse();
    }
}

class AppTest extends TestCase
{
    public function test()
    {
        $fooStub = $this->createMock(Foo::class);

        $bar = new Bar;
        $bar->run($fooStub);
    }
}
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
