### ISSUE TITLE
PhpUnit 6.4 CodeCoverage issue for Exception marking

### ISSUE THREAD

**Issue by KestutisIT** [sebastianbergmann/phpunit#2842]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.1.10
| WP Version         | 4.9-RC1-42049-src
| Installation Method | PhpUnit 2017.2.4 (Run Configuration) / PHAR PATH

Code Coverage does not mark as 'Green' the covered exception. While the test log says it passed the test - that means it got request exception of setting disallowed variable. But that is not shown in code coverage.

![phpunit 6 4 3 codecoverage issue for exception - 1](https://user-images.githubusercontent.com/4975202/32473006-092756b8-c36e-11e7-8fbf-521f89a66602.jpg)
![phpunit 6 4 3 codecoverage issue for exception - 2](https://user-images.githubusercontent.com/4975202/32473007-094dc12c-c36e-11e7-8bf5-d897a811c814.jpg)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

Also please paste code instead of using screenshots of code.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
