### ISSUE TITLE
PHPUnit --coverage-html showing 0% rather than actual coverage

### ISSUE THREAD

**Issue by archana27m** [sebastianbergmann/phpunit#2848]
PHPUnit version     | 6.3.0
PHP version         | 7.0.15
XDebug | 2.5.4
Installation Method | Composer 

Composer.json
```
"require-dev": {
         "phpunit/phpunit": "6.3.0"
    }
```

I have my php class files inside lib folder and unit test cases inside tests folder.
Using phpunit.xml as follows: 
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
  <testsuites>
    <testsuite name="ProjectName">
      <directory suffix="Test.php">tests</directory>
    </testsuite>
  </testsuites>
<filter>
    <whitelist addUncoveredFilesFromWhitelist="true">
      <directory suffix=".php">./lib</directory>
    </whitelist>
  </filter>
</phpunit>
```

The coverage html files getting generated but showing code coverage as 0% for all files.
Please help me on this.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
