### ISSUE TITLE
Different coverage reports on local dev machine and Travis

### ISSUE THREAD

**Issue by antonioribeiro** [sebastianbergmann/phpunit#2883]
| Q                   | Travis | Local
| --------------------| ---------------|------
| PHPUnit version     | 6.4.4| 6.4.4
| PHP version         | 7.1.12| 7.1.8
| Installation Method | Composer / PHAR| Composer / PHAR

As per the images below, of course `PragmaRX\Version\Package\Console\Commands\Refresh` was not being tested, but why I'm getting a 100% coverage in my local dev machine?

### Development host

![image](https://user-images.githubusercontent.com/3182864/33406312-5b1d6722-d553-11e7-924b-ee7e2ac3a1f4.png)

### Travis

![image](https://user-images.githubusercontent.com/3182864/33406344-7ce22820-d553-11e7-88dc-e5895c4f0ab4.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
