### ISSUE TITLE
Mocking class with method 'provide' fails since 6.5.x

### ISSUE THREAD

**Issue by frederikbosch** [sebastianbergmann/phpunit#2891]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.0-1
| PHP version         | 7.1.12
| Installation Method | Composer

Since version 6.5.0 I have problems with mocking a specific class: `DomainProviderInterface`. It seems to be related to the method `provide` that is part of the class.

```php
namespace Genkgo\TestFramework;

use PHPUnit\Framework\TestCase;

final class DomainNameCollection {}

interface DomainProviderInterface {
    public function provide(): DomainNameCollection;
    public function persist(DomainNameCollection $domains): void;
}

final class Test extends TestCase {
    public function test() {
        $mock = $this->createMock(DomainProviderInterface::class);
        $this->assertInstanceOf(DomainProviderInterface::class, $mock);
    }
}
```

Above code works in 6.4.x, but fails in 6.5.x. I tested both 6.5.0 and 6.5.1.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by frederikbosch** [comment]
Thanks, see https://github.com/sebastianbergmann/phpunit-mock-objects/issues/388 now.
