### ISSUE TITLE
Is it possible to stub a method to return array?

### ISSUE THREAD

**Issue by raghavendra89** [sebastianbergmann/phpunit#2962]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.0.22
| Installation Method | Composer

I did check the documentation and looked into the `will()`, `willReturn()` methods. I'm trying to stub a method to return an array. But I'm only getting the first array value as return data. In this case it is 'random_id'.

**Is it possible to stub a method to return the complete array?**

```
public function testCreateFolder()
{
    $user = factory(User::class)->make();

    $localStorageService = $this->createMock(LocalStorageService::class);

    $localStorageService->method('createFolder')
            ->willReturn(array('folder_id' => 'random_id', 'folder_path' => ("/Users/" . $user->email)));
    ...
}
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
