### ISSUE TITLE
Code Coverage is getting slow when i use whitelist->exclude node.

### ISSUE THREAD

**Issue by mahmutbayri** [sebastianbergmann/phpunit#2965]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.26
| PHP version         | 7.1.13
| Installation Method | PHAR

Hi, i have a big project has many php files. I want to report Code Coverage. In order to get get faster results i exclude some directories using whitelist->exclude node, bu i get slower result.

Sample Filter configuration

```
<filter>
    <whitelist>
        <directory suffix=".php">./Modules</directory>
    </whitelist>
</filter>
```

Sample Filter configuration 2

```
<filter>
    <whitelist>
        <directory suffix=".php">./Modules</directory>
        <exclude>
            <directory>./Modules/*/Resources</directory>
        </exclude>
    </whitelist>
</filter>
```

I did some test with blackfire tools, and saw  that RecursiveDirectoryIterator::hasChildren method calls more if i use exclude node.

With "exclude" node: 51.357 times
Without "exclude" node: 20.006 times

What am I doing wrong?

Thanks.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
