### ISSUE TITLE
Getting Started (5.3,5.4,5.5) incorrect code sample.

### ISSUE THREAD

**Issue by thinsoldier** [sebastianbergmann/phpunit#2968]
https://phpunit.de/getting-started-with-phpunit-for-php53.html

> PHP Fatal error:  Call to undefined method EmailTest::expectException() in tests/EmailTest.php on line 16

No method named `expectException` exists in the `PHPUnit_Framework_TestCase` class in phpunit/src/Framework/TestCase.php in PHPUnit version 4.

    $this->expectException(InvalidArgumentException::class);

should be

    $this->setExpectedException(InvalidArgumentException::class);

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-website](https://github.com/sebastianbergmann/phpunit-website) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by thinsoldier** [comment]
Sorry. I should have looked around more before posting.
