### ISSUE TITLE
DBUNIT extension don't load anymore

### ISSUE THREAD

**Issue by jrichard689** [sebastianbergmann/phpunit#2993]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.1.2
| Installation Method | PHAR

Runnig PHPUNIT with DBUNIT extension don't work since 7.0.0 update 

 `php phpunit.phar -c phpunit.xml --verbose myTest.php
`

Result of the command:

```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.2 with Xdebug 2.5.5
Configuration: phpunit.xml
Extension:     tools_phpunit\dbunit.phar is not compatible with this version of PHPUnit

```

Start of the phpunit xml file:
```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/7.0/phpunit.xsd"
         extensionsDirectory="tools_phpunit">
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [dbunit](https://github.com/sebastianbergmann/dbunit) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by jrichard689** [comment]
Reported on the dbunit project
