### ISSUE TITLE
Add support of any iterable in  Matcher_ConsecutiveParameters

### ISSUE THREAD

**Issue by velosipedist** [sebastianbergmann/phpunit#3005]
For being able to do this, without filling excessive arrays describing expected dynamic params sets.

```php
$mock->expects(self::atLeastOnce())
  ->method('foo')
  ->withConsecutive(function(/* mocked instance ?*/) {
      $i = 0;
      yield ['constantParam', $i++, 'etc'];
});
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
