### ISSUE TITLE
Could not use "PHPUnit_TextUI_ResultPrinter" as printer: class does not exist

### ISSUE THREAD

**Issue by MagicMarvMan** [sebastianbergmann/phpunit#3055]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.0
| PHP version         | 7.1.9
| Installation Method | Travis: Pre installed

Hello,

When I try to test my project (https://github.com/contentmonkey/contentmonkey) with Travis and PHPUnit, the same error always occurs:
```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

Could not use "PHPUnit_TextUI_ResultPrinter" as printer.
```

When I try to test my project on my local Mac, using PHP 7.2.3 and PHPUnit 7.0.3 the same error occurs in another form:
```
PHPUnit 7.0.3 by Sebastian Bergmann and contributors.

Could not use "PHPUnit_TextUI_ResultPrinter" as printer: class does not exist
```

On my Travis environment `PHPUnit` was pre-installed and on my mac I installed it using homebrew.

Thank you for your help,
MagicMarvMan

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by MagicMarvMan** [comment]
No, I've triple-checked that. I only have one version of PHPUnit installed. I solved the issue by using what-the-jeff's nyancat-phpunit-resultprinter. But I am still searching a solution where I can use the default printer.

**Comment by grandopener** [comment]
I'm not sure this should have been closed so quickly.  I discovered a similar problem in that phpunit (as installed by composer) absolutely refuses to run unless the current directory is where phpunit is installed.  Example on a clean VM where phpunit is not otherwise installed:

This results in the "class does not exist" error mentioned above:
```
cd /src/myproject
composer install
./vendor/bin/phpunit .
```

This results in tests actually running:
```
cd /src/myproject
composer install
cd vendor/bin
./phpunit /src/myproject
```

I'm not familiar enough with phpunit to usefully debug this further, but I'm happy to provide more information.

The project in question contains a phpunit.xml that specifically names PHPUnit_TextUI_ResultPrinter as the printer class, and contains a tests folder with a number of test files.  The `vendor/autoload.php` file does not have any unusual configuration.  Its entire contents are as follows:
```
<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitdc143e691329152196917934125770f4::getLoader();
```

Verified these same results with phpunit 6 and 7.  (The legacy project I'm trying to get running doesn't currently work at all with phpunit 8.)

This problem (or something like it) is apparently quite common--this issue (and similar #2776) are some of the top results for Google searching "PHPUnit_TextUI_ResultPrinter".

**Comment by pengyue** [comment]
You can keep ResultPriner in the phpunit.xml,
I use PHP7.2.4 and PHPUnit 6.5, phpunit starts to use proper namespace like `PHPUnit\\TextUI\\ResultPrinter` instead of `PHPUnit_TextUI_ResultPrinter`, so it works for me with `vendor/bin/phpunit tests/unit --printer PHPUnit\\TextUI\\ResultPrinter`
