### ISSUE TITLE
Prefer assertException over expectException

### ISSUE THREAD

**Issue by jchook** [sebastianbergmann/phpunit#3071]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.7
| PHP version         | 7.1.16
| Installation Method | PHAR

**Goal:** to test exceptions.

After reading through [SO](https://stackoverflow.com/questions/5683592/phpunit-assert-that-an-exception-was-thrown) I found #1798, which was closed in a routine issue clean-up. As suggested, I am re-opening this issue.

Please forgive any ignorance I have about the design decisions of the `expectException` family of methods, but I still find this particular suggestion to be a good direction on having a callback-based exception testing pattern.

```php
/**
 * @param string $type
 * @param string|null $message
 * @param callable $function
 */
protected function assertException($type, $message, callable $function)
{
    $exception = null;

    try {
        call_user_func($function);
    } catch (Exception $e) {
        $exception = $e;
    }

    self::assertThat($exception, new PHPUnit_Framework_Constraint_Exception($type));

    if ($message !== null) {
        self::assertThat($exception, new PHPUnit_Framework_Constraint_ExceptionMessage($message));
    }
}
```

While I realize this example is far from a complete replacement, I think we could build from this pattern to give users more control over exception testing, and a more familiar assertion pattern that doesn't require calling `$this->fail()`, etc.

Here is a theoretical usage example (of a currently non-existent `assertException`):

```php
$this->assertException(MyException::class, 'doStuff', 
  function($exception, $phpUnit) {
    $phpUnit->assertEquals('Some message', $exception->getMessage());
    $phpUnit->assertEquals(123, $exception->getCode());
    $phpUnit->assertEquals('custom value', $exception->getCustomThing());
  }
);
```

**Comment by sebastianbergmann** [comment]
I wrote everything I have to say on the subject in https://thephp.cc/news/2016/02/questioning-phpunit-best-practices.

IMO, `expectException()` and friends are all that is needed.

**Comment by jchook** [comment]
Thanks for the link.

**Comment by jchook** [comment]
As you mention in your post, the suggestion has [been brought up](https://www.reddit.com/r/PHP/comments/44a8hx/thephpcc_questioning_phpunit_best_practices/czos9il/), dismissed, and [implemented as a plugin](https://github.com/Codeception/AssertThrows) by others.

Quoting your link:

> The argument that is made in favor of this approach is that it allows checks for multiple exceptions within a single test. In my opinion, though, this is an argument against it. A unit test should be fine-grained and only test a single aspect of one object. Why would you need to check for different exceptions in a single test?

Here are a few additional arguments surrounding the case:

1. Currently we are forced to use the confessedly less desired "return or fail", etc techniques to test any other aspects of an exception beyond the message, code, and class.

2. The `assert` syntax is ubiquitous in PHPUnit, *except exceptions*. This is a clear and isolated break in expectations for the syntax.

3. It's how [Facebook's Jest](https://facebook.github.io/jest/docs/en/expect.html#tothrowerror), [Chai](http://www.chaijs.com/api/bdd/#method_throw), [Codeception](https://codeception.com/docs/modules/Asserts.html#algolia:p:nth-of-type(29)), [NUNIT](http://nunit.org/docs/2.5/exceptionAsserts.html), and many others do it, and it's how we expect it to be done. Alternatives such as annotations and calling `$this->fail()` are seen as [less optimal](https://stackoverflow.com/questions/5683592/phpunit-assert-that-an-exception-was-thrown#comment35537684_5683605) by the community.

4. IMO, testing a single "aspect" of one object isn't always 1-to-1 with testing a single exception of an object. Forcing users to separate tests by exception is sometimes overkill, especially if it requires `@depends`, etc.

**Comment by jchook** [comment]
@Pictor13 If you're interested I implemented [`$this->assertThrows()`](https://github.com/jchook/phpunit-assert-throws) as a PHP trait.

I'd be happy to submit a PR if @sebastianbergmann would like.

Also @keradus interested to hear what you have to add.

**Comment by gingerCodeNinja** [comment]
So, I have some code that `throws FooException($message, $bar)`. I want to test the code that throws this exception, that it passes in the correct `$bar`, but I can't do that with `expectException`/`expectExceptionMessage`.

I was hoping on having a callback that can test FooException ->getBar() matches my expectation, like I can do for assertions. Seems silly to have to use a plugin for something that is so core to PHP.

Since PHPUnit does not support this right now, and I can't easily use a plugin (enterprise software etc), I guess I will have to not use expectException, and wrap the method under test with try/catch in my actual test class, catch the exception and run my assertions.

**Comment by eithed** [comment]
I can't use `expectException` when there's a cleanup step involved and I have to remember that everything after `expectException` will **not** execute, which is counter-intuitive. As such this:

```
public function test_duplicate_data_is_not_saved()
{
    $this->expectException(DuplicateEntryException::class);
    $this->service->insert('foo');
    
    // throws DuplicateEntryException
    $this->service->insert('foo');

    // clear data
    $this->service->delete('foo');
}
```

will leave me with foo entry, even though test succeeds and I think that `delete` line fires. I've to do following for it to work as expected:

```
public function test_duplicate_data_is_not_saved()
{
    $this->service->insert('foo');
    
    try {
        $this->service->insert('foo');
    } catch (\Exception $e) {
        $this->service->delete('foo');
        $this->assertInstanceOf(DuplicateEntryException::class, $e);
    }
}
```

One needs to remember as well that `tearDown` won't trigger in the first scenario.

**Comment by Pictor13** [comment]
Why would `tearDown` not be triggered? You sure? (note: I didn't try it)
That's the correct method to use to cleanup or reset your service.

Also, your alternative is correct:`try/catch/finally` is the only way I would expect _any_ code to be still executed after an exception has been thrown.

**Comment by renepupil** [comment]
> I wrote everything I have to say on the subject in https://thephp.cc/news/2016/02/questioning-phpunit-best-practices.

@sebastianbergmann This link is dead.

**Comment by sebastianbergmann** [comment]
https://thephp.cc/articles/questioning-phpunit-best-practices

**Comment by jdevinemt** [comment]
> https://thephp.cc/articles/questioning-phpunit-best-practices

I agree with your reasoning here @sebastianbergmann. I would also argue that it is best not to combine the 'act' and 'assert' parts of the AAA (Arrange, Act, Assert) methodology into a single method.

I originally came here because I was looking for a way to keep my 'Arrange', 'Act' and 'Assert' test parts in that order and was looking for a way to do that in PHPUnit. But I realized the best way to do this is by simply using a try/catch in the 'Act' phase and perform my assertions on it.

**Comment by achertovsky** [comment]
i have same question @renepupil has

**Comment by KinaneD** [comment]
Same here, i don't have any arguments against placing the `$expectException` before the Act step, yet i am interested in further asserting changes/events results of the exception being throw.

I must say that i find it counter intuitive to use a try/catch block in a test when `$exceptException` exit, but as @renepupil showed in the example above, it was the approach i took to circumvent the fact that processing the test is interrupted when the exception is thrown.

Generally speaking, I would expect the `$expectException` to behave just like any other assertion, if the expectation is met the continue in the test rather than interrupt it.

**Comment by Kuroki-g** [comment]
Almost same idea with @mfn

I prefer to the idea of Record.Exception (https://github.com/xunit/xunit/blob/master/src/xunit.core/Record.cs#L19) in xunit

```
class Helper
{
    public static function Exception(\Closure $func) : \Throwable
    {
        try {
            $func();
        } catch (\Throwable $t) {
            return $t;
        }
        return null;
        //  Or use fail() in PHPUnit
    }
}
```

Usage
```
function some_func()
{
    throw new Exception("Message");
}

class SampleTest extends TestCase
{
    public function test_sample1()
    {
        $expected = "Message!";

        $actual = Record.Exception(fn() => some_func());

        self::assertEqual($expected, $actual->getMEssage());
    }
}
```
