### ISSUE TITLE
Tests working when shouldn't due to whitelist calling require_once

### ISSUE THREAD

**Issue by pelallemant** [sebastianbergmann/phpunit#3100]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | "phpunit/phpunit": "^6.1"
| PHP version         |  7.0.28
| Installation Method | Composer

Hi, when I add the following code in my phpunit.xml, all the sources are included by phpunit before executing tests.

```
<filter>
    <whitelist processUncoveredFilesFromWhitelist="true">
      <directory suffix=".php">../src</directory>
    </whitelist>
  </filter>
```

By doing this, if we failed the namespace of a file, our autoloaders functions are never called so the tests do work but when running the app normally it doesn't because our autoloaders can't find the files.

I don't know why you require those files, but couldn't it be possible to do it in another context (executed by a child program) ?

Best regards

**Comment by sebastianbergmann** [comment]
You set `processUncoveredFilesFromWhitelist="true"` in your `phpunit.xml` and report its effect as a bug.

* `addUncoveredFilesFromWhitelist="false"` means that only whitelisted files that have a least one of line of executed code are included in the code coverage report
* `addUncoveredFilesFromWhitelist="true"` (default) means that all whitelisted files are included in the code coverage report even if not a single line of code of such a file is executed
* `processUncoveredFilesFromWhitelist="false"` (default) means that a whitelisted file that has no executed lines of code will be added to the code coverage report (if `addUncoveredFilesFromWhitelist="true"` is set) but it will not be loaded by PHPUnit and it will therefore not be analysed for correct executable lines of code information
* `processUncoveredFilesFromWhitelist="true"` means that a whitelisted file that has no executed lines of code will be loaded by PHPUnit so that it can be analysed for correct executable lines of code information

By the way, this [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
