### ISSUE TITLE
Code-coverage cannot capture closure or anonymous functions

### ISSUE THREAD

**Issue by ajcastro** [sebastianbergmann/phpunit#3109]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 7.0.3
| PHP version         | PHP 7.2.4
| Installation Method | Composer

![image](https://user-images.githubusercontent.com/4918318/39406336-c6a30cda-4be7-11e8-8e7a-e9872bfb52e7.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
