### ISSUE TITLE
Coverage reports failing

### ISSUE THREAD

**Issue by renanrosalojasmm** [sebastianbergmann/phpunit#3118]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1.5
| PHP version         | 7.2.5
| Installation Method | PHAR

When I try to generate the test coverage reports I get the error code 255.
This is the section in my phpunit configuration file where I declare the reports:

```
<logging>
         <log type="coverage-html" target="../build/coverage"/>
         <log type="coverage-clover" target="../build/logs/clover.xml"/>
         <log type="coverage-xml" target="../build/logs/coverage"/>
         <log type="junit" target="../build/logs/junit.xml"/>
</logging>
```
If I remove the coverage logs, phpunit runs with no error.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
