### ISSUE TITLE
Coverage report exclude open brackets

### ISSUE THREAD

**Issue by johnroyer** [sebastianbergmann/phpunit#3164]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.4
| PHP version           | 7.1.16
| Installation Method | Composer
| Composer version | 1.6.5
| Xdebug version    | 2.6.0

I run PHPUnit with `--coverage-html PATH` parameter. The report seems a little weird. All line is covered, excluding open bracket.

![2018-06-12 11 15 24](https://user-images.githubusercontent.com/114491/41268390-65e7c4ae-6e32-11e8-9483-ee5a955d24c0.png)

I notice that this problem maybe cause by Xdebug or other libraries (#1539).  Is there any way to fix it ?

Thanks

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by johnroyer** [comment]
Still helps. Thanks a lot. 
: D
