### ISSUE TITLE
Documentation missing for PHPUnit 7.2 on https://phpunit.readthedocs.io

### ISSUE THREAD

**Issue by jleeothon** [sebastianbergmann/phpunit#3221]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.x

### Problem

Documentation for PHP 7.2 is not available on https://phpunit.readthedocs.io

### What I did

- Went to phpunit.de
- Clicked the "Documentation" tab
- Go redirected to https://phpunit.readthedocs.io
- Try to change the versions to PHP 7.2

### What I got

- Only 7.0 and 7.1 available

### What I expected

- PHP 7.2 to be available.

### Relevant extra information

<img width="344" alt="screen shot 2018-07-20 at 18 43 05" src="https://user-images.githubusercontent.com/6202537/43014572-e92aa650-8c4c-11e8-9424-921c8cec6fcd.png">

### Other

- The XML schema for `phpunit.xml` has changed, and now I get errors like e.g. `- Element 'exclude': Element content is not allowed, because the type definition is simple.` but the example schemas under https://phpunit.readthedocs.io/en/7.1/ do not have a simple definition for the `exclude` element.
- I checked https://phpunit.readthedocs.io/en/7.2/, but get a `Permission Denied` message.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
