### ISSUE TITLE
Custom loader is ignored

### ISSUE THREAD

**Issue by nebososo** [sebastianbergmann/phpunit#3227]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | Reproduced on 6.5.2 and 7.2.6
| PHP version         | 7.2.7
| Installation Method | repository

A custom loader defined with testSuiteLoaderClass and testSuiteLoaderFile is instantiated but not used.

This can be reproduced by creating a simple project like this:

> phpunit.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
  testSuiteLoaderClass="CustomLoader"
  testSuiteLoaderFile="loader.php"
  colors="true" >
    <testsuites>
        <testsuite name="somesuite">
            <directory suffix=".php">tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

> tests/something.php

```
<?php
class Tests_Something extends PHPUnit\Framework\TestCase {
	public function test_something() {
		$this->assertNotFalse( true );
	}
}
```

> loader.php

```
<?php

class CustomLoader implements PHPUnit\Runner\TestSuiteLoader {
	public function __construct() {
		var_dump('__construct() called');
	}
	public function load(string $suiteClassName, string $suiteClassFile = ''): ReflectionClass {
		var_dump("LOADING $suiteClassName");
		die;
	}
    public function reload(ReflectionClass $aClass): ReflectionClass {
		var_dump('reloading');
		die;
	}
}
```

The expected behavior would be seeing the construct message followed by a single load message then die. But instead, we get:

```
string(20) "__construct() called"
PHPUnit 7.2.6 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 61 ms, Memory: 8.00MB

OK (1 test, 1 assertion)
```
Looking at the code. `$loader->load()` is only called in `BaseTestRunner::loadSuiteClass()`, which is only called in `BaseTestRunner::getTest()`. This is called in `Command::run()` only if `$arguments['test']` is not an instance of `Test`, but `Command::handleArguments()`, called just a few lines earlier, exits with an error if `$arguments['test']` is not set.

It seems like the loader will never be used.

**Comment by mstolt** [comment]
This is exactly what I still experience. I am currently using PHPUnit 8.1 on PHP 7.3. Is there any chance for a comment from Sebastian on this. Pointing us to the correct way of using the options testSuiteLoaderClass and  testSuiteLoaderFile ?

Kind regards
  Matthias

**Comment by sebastianbergmann** [comment]
I do not remember why `testSuiteLoaderClass` (and `testSuiteLoaderFile`) was added. In hindsight, I think it was wrong to add it.

According to this ticket, `testSuiteLoaderClass` does not work (anymore). Instead of fixing it, I would rather remove it.

**Comment by mstolt** [comment]
What a pity.  
Is there any other "official" way to intercept the loading/running of suites/TestCases?

Actually we would need such an option to run Integration Tests with PHPUnit on Variants of a Base Project. Our Code Base is a Base for several "Instances" for different customers that do have some parts replaced/changed. So we like to run mostly the Base TestCase and in some occasions replace the Base TestCase with a Customized TestCase Version for a specific Variant. Since e.g. 95% of the tests are the same for the Base and the Variant, we do not want to replicate all TestCase Classes (by inheriting them from the Base TestCase), but we would like to look up if a specialized version exists (same Classname in a different Namespace) and run that version of the TestCase instead of the Base TestCase. 

So an option to "enhance" the Test Suite Loader/TestCase Loader/Runner would be great.

**Comment by mstolt** [comment]
Hi,
just in case some other might stumble in this thread. Our solution to the problem was a self written configuration file generator. So no need for any poking around in the PHPUnit Runner or TestSuitLoading mechanism anymore.

The generator simply creates different "phpunit.xml" files for the different variants. In those files are the TestCase classes explicitly referenced. So there is no "doubt" on which TestCase to run. The variant TestCases can still inherit from the base TestCases and every scenario I can dream of is buildable with this approach.

Thanks to the great modularization of the PHPUnit project we could reuse several components of it for the generator script. It was actually fun to write.

Thanks Sebastian for given us these tools.
