### ISSUE TITLE
7.5.7 class \Failure not found during class teardown exception

### ISSUE THREAD

**Issue by rtek** [sebastianbergmann/phpunit#3564]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.7
| PHP version         | 7.1.19
| Installation Method | Composer

Throwing an exception from tearDownAfterClass results in fatal error:

```
<?php

class Bug extends \PHPUnit\Framework\TestCase
{
    static public function tearDownAfterClass()
    {
        throw new \Exception('bug');
    }

    public function testBug()
    {
        $this->fail();
    }
}
```

```
$ vendor/bin/phpunit tests/Bug.php  --debug --verbose
PHPUnit 7.5.7 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.19 with Xdebug 2.5.3
Configuration: phpunit.xml.dist

Test 'Bug::testBug' started
Test 'Bug::testBug' ended
PHP Fatal error:  Uncaught Error: Class 'Failure' not found in vendor\phpunit\phpunit\src\Framework\TestSuite.php:761
Stack trace:
#0 vendor\phpunit\phpunit\src\TextUI\TestRunner.php(641): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#1 vendor\phpunit\phpunit\src\TextUI\Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#2 vendor\phpunit\phpunit\src\TextUI\Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#3 vendor\phpunit\phpunit\phpunit(61): PHPUnit\TextUI\Command::main()
#4 {main}
thrown in vendor\phpunit\phpunit\src\Framework\TestSuite.php on line 761

Fatal error: Uncaught Error: Class 'Failure' not found in vendor\phpunit\phpunit\src\Framework\TestSuite.php on line 761

Error: Class 'Failure' not found in vendor\phpunit\phpunit\src\Framework\TestSuite.php on line 761

Call Stack:
0.0000     368768   1. {main}() vendor\phpunit\phpunit\phpunit:0
0.0060    1162648   2. PHPUnit\TextUI\Command::main() vendor\phpunit\phpunit\phpunit:61
0.0060    1171440   3. PHPUnit\TextUI\Command->run() vendor\phpunit\phpunit\src\TextUI\Command.php:162
0.0160    2951704   4. PHPUnit\TextUI\TestRunner->doRun() vendor\phpunit\phpunit\src\TextUI\Command.php:206
0.0250    3275088   5. PHPUnit\Framework\TestSuite->run() vendor\phpunit\phpunit\src\TextUI\TestRunner.php:641
--

**Comment by sebastianbergmann** [comment]
@epdenouden In 96c1264e32b74ede86612df73416097b72aae64d, you added `$test  = new \Failure('tearDownAfterClass');`.

`\Failure` is not part of PHPUnit's production code but rather part of its test suite's fixture. This is why the tests for PHPUnit's own test suite work (because `\Failure` is available then). When PHPUnit's own test suite's fixture is not available, which, obviously ;-), is the default case, then `\Failure` does not exist.

**Comment by sebastianbergmann** [comment]
@epdenouden Can you take care of this? If not, I can look into it (but would first have to dig into the changes you made there).

**Comment by epdenouden** [comment]
> `\Failure` is not part of PHPUnit's production code but rather part of its test suite's fixture.

I was the first thing I thought when I saw the bug and immediately thought about `\Failure`. Will look into the 'synthetic error' mechanism to or some other way to inject a placeholder test. Will clean this up properly.

@rtek Thanks for the detailed report! As @sebastianbergmann mentions, this wouldn't have been much harder to find otherwise and I completely overlooked it the first time around.
