### ISSUE TITLE
Tests for test result cache depend on PHP implementation details

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3581]
@krakjoe informed me that some of the test failures of #3526 are likely due to changes to `serialize()` / `unserialize()`. PHPUnit's tests should not depend on implementation details like that.

**Comment by epdenouden** [comment]
Agreed. I'll upgrade the cache to use a more generic format.

**Comment by krakjoe** [comment]
Designing your own format isn't necessary, you can depend on the
functionality without depending on exchange format.

**Comment by epdenouden** [comment]
> Designing your own format isn't necessary, you can depend on the functionality without depending on exchange format.

Hi @krakjoe! This is very likely true, but the I haven't looked into the specifics of the bug. The `ResultCache` also uses (un)serialization wrangling of the data. The `serialize()` format is rather cumbersome to read, making debugging bugs like these a chore without tools. When building the feature I had small workbench set up just for this.

The reason I used the PHP-native `serialize()` is because I needed a quick way to dump data to a file in a common format that didn't require an external library. I'm guessing the reason this got filed on April 2 is because I would have refactored it with `fputcsv()` yesterday?

**Comment by krakjoe** [comment]
I've looked a little closer at the failure that provoked me to make the comment that provoked this issue, it may not be related to serial format ...

I'll look closer still when I've got another hour (hopefully later today) ...

Regardless of what is causing this particular failure, I was making the comment that depending on the format of serialized variables is not very smart, because it's not a format we make any guarantees about - if during the release cycle for any version of PHP, we discover that it must change for security (or indeed any other) reasons, then change it must and it will break this kind of test.

If you want to test if serialize/unserialize is working properly, then execute them, but don't depend on the details of the exchange format would be my advice.

**Comment by epdenouden** [comment]
> but don't depend on the details of the exchange format would be my advice.

And that's very good advice! :-) I do use the output format in one of the PHPT tests to see what would be written to the filesystem. I'll fix this to better tests the lifecycle of the data in the cache, instead of the cachefile itself.

**Comment by sebastianbergmann** [comment]
Should be taken care of by 3e3aecdeb1160de5500fa7715436e73689cc11a3.
