### ISSUE TITLE
Mock docblock

### ISSUE THREAD

**Issue by kerryatlanta** [sebastianbergmann/phpunit#3606]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.8
| PHP version         | 7.2.16
| Installation Method | Composer

Note: using PHPUnit v7 for wordpress testing compatibility

[I am building an app that implements custom docblock annotations using the Doctrine Annotations library.](https://stackoverflow.com/q/55750812/3207129)

Currently, I'm creating test classes with test docblocks and annotations, and passing them in via dataProvider.

It would be much more efficient to be able to create mock docblocks, perhaps kind of like this, for example:

`$foo = $this->getMockBuilder("nonexistant")
    ->setMockClassName("TestClass")
    ->setMockClassDocblock("/** @SomeAnnotation("foo") */")
    ->getMock();`

In addition to classes, would need setMockPropertyDocblock and setMockMethodDocblock

Thanks for your consideration of my issue!

[composerinfo.txt](https://github.com/sebastianbergmann/phpunit/files/3098175/composerinfo.txt)

**Comment by Ocramius** [comment]
Hey @kerryatlanta! I discussed this in detail with @sebastianbergmann, and I think the feature should not be considered for adoption.

There are two issues with this proposal:

 1. philosophical
 2. technical

## Philosophical issue

Mock objects are supposed to be behaviors bound to a static definition that is already provided in the repository. In practice, you have a definition of a symbol `Foo`, and you want an implementation that stubs and/or spies over a certain interaction with your system under test. The static definition of this object is still `Foo`, not the mock.

This affects both your request of annotating (annotations are static definitions of your tests) your tests and similar functionality that relies on reflecting mocks, getting the class name of a mock and further introspection of types of mocks.

That is out of scope for a mock generator: you want to use a real hand-crafted stub that presents all the type and metadata (annotations) alterations that your SUT may be relying upon. The mock itself limits itself with altering runtime behavior of known object API.

## Technical issue

You seem to be wanting to use `>setMockClassDocblock("/** @SomeAnnotation("foo") */")` in order to declare annotations like the ones in [`doctrine/annotations`](https://github.com/doctrine/annotations): this won't work due to how mock code is being loaded through `eval()`.

Take following example:

```php
<?php

namespace A;

use My\CustomAnnotation;

/** @CustomAnnotation */
class Foo
{
}
```

In this snippet, `doctrine/annotations` would need to load the entire source in order to understand that `@CustomAnnotation` refers to `My\CustomAnnotation`. That code is long gone when `eval($code)` is used, and it is impossible to perform this operation at runtime, unless a readable file exists. This is a limitation of the engine.

## Conclusion

This feature, while maybe interesting at first glance when interacting with tooling that heavily relies on annotations, is both going against the mock system expected usage (declaring new static symbols, metadata and API) and against technical limitations in the language.
