### ISSUE TITLE
Running PHPUnit tests in Eclipse generates a java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by fdirson-OpenGateway** [sebastianbergmann/phpunit#3753]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.13
| PHP version         | 7.3.1
| Installation Method | Composer 

PHPUnit don't run in Eclipse with JAVA 11.
See https://stackoverflow.com/questions/52260964/running-phpunit-tests-in-eclipse-generates-a-java-util-concurrentmodificationexc

If i launch eclipse with JAVA 8, it's OK because automatically this environnement var is add:
PHPUNIT_PORT 7478
With JAVA 11 (oracle or adoptOpenJdk binaries) this env var is not set and following error is thrown:
java.util.ConcurrentModificationException
If manually i add this var, runs are OK...

In Eclipse, i have two ways for launch phpunit tests (with Same error and same solve): 
 - Right click on phpunit.xml and "run as phpunit test"
 - Right click on each TestClass and "run as phpunit test"

Best regards,

F.DIRSON

**Comment by sebastianbergmann** [comment]
This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests.

Please report issues with regards to IDE integration to the vendor of your IDE.

**Comment by epdenouden** [comment]
@fdirson-OpenGateway As I suspected this issue is related to a custom logger used by Eclipse. The reason is translation of logging output format and to handle minor changes between versions of each package.

PHPUnit uses very few environmental settings in an effort to be as isolated as possible, and PHPUNIT_PORT is never mentioned in the codebase. A quick search showed Eclipse using something called `PHPUnitLogger` and I am guessing the `PHPUNIT_PORT` is either to connect to PHPUnit as an isolated subprocess or to talk to Xdebug for tracing.

As @sebastianbergmann noted this is an issue to be filed with the Eclipse PHP UI team.

**Comment by fdirson-OpenGateway** [comment]
Thanks,

Reported at https://www.eclipse.org/forums/index.php/m/1809167/
