### ISSUE TITLE
returnValueMap only works with at least 3 input parameters

### ISSUE THREAD

**Issue by miertschink** [sebastianbergmann/phpunit#404]
I'm trying to use returnValueMap as described here:
http://www.phpunit.de/manual/3.6/en/test-doubles.html#test-doubles.stubs.examples.StubTest5.php

It seems that it only works when using 4 elements in the array's
when trying like this:

```
    $map = array(
        array('foo', 'bar'),
    );

    $myClass= $this->getMock('myClass');
    $myClass->expects($this->any())
        ->method('myMethod')
        ->will($this->returnValueMap($map));
```

It doesn't work...
a dump of $invocation->parameters in method 'invoke' of class PHPUnit_Framework_MockObject_Stub_ReturnValueMap
comes up with 

```
    array(3) {
      [0]=>
      string(11) "foo"
      [1]=>
      NULL
      [2]=>
      bool(false)
    }
```

why are there NULL and false added?

**Comment by b01** [comment]
HA! This has been getting me for a while. I've wanted to use returnValueMap for a while, but have been avoiding because I could never figure out how to make it return the correct value. The optional parameters of methods I didn't write were the pitfall. I wish the documentation pointed that out, like "**NOTE** Remember to check the signature of the method you're stubbing and don't forget to fill in optional parameters."

Better documentation would have helped me.

**Comment by sw4n** [comment]
But what about more than 3 arguments in a mocking method? And I need pass 4 arguments in a method, for example. What should I do with such situation?

**Comment by raddi00** [comment]
<?php

class mockingTest extends PHPUnit_Framework_TestCase {

    public function testMocking() {
        $mock = $this->getMock('MockMe');
        $mock->expects($this->once())
            ->method('stuff')
            ->will($this->returnValueMap(
                array(array('foo', 'bar'))
            )); 

        $this->assertSame('bar', $mock->stuff('foo'));
    }   

}

class MockMe {

    public function stuff($a) {
        die('I said mock me!');
    }   

}
