### ISSUE TITLE
Actual size is wrong in assertCount with generators

### ISSUE THREAD

**Issue by spaceemotion** [sebastianbergmann/phpunit#4229]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.4
| PHP version         | 7.4.0
| Installation Method | Composer

#### Summary

The original sample at https://github.com/sebastianbergmann/phpunit/issues/3302#issuecomment-420984415

```php
   public function testGenerator()
    {
        $generator = static function () {
            yield 1;
            yield 2;
            yield 3;
        };

        static::assertCount(3, $generator());
        static::assertCount(4, $generator());
    }
```

no longer seems to work when trying to assert the count of four. The error message spits out the following instead:

`Failed asserting that actual size 0 matches expected size 4`

#### Current behavior

I initially came across this in my own code, but found the example linked above. My generator definitely holds some values, and is being iterated in the assertCount() check, but the error message is just wrong.

#### How to reproduce

Just execute the example linked above.

#### Expected behavior

Something along the lines of:

`Failed asserting that actual size 3 matches expected size 4`

**Comment by amenning** [comment]
I found this was because the generator cannot be cloned and can only be iterated over once.  The actual count was correctly determined in the [matches](https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/Constraint/Count.php#L44) function.  However, then the [failureDescription](https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/Constraint/Count.php#L119) attempts to iterate over the generator a second time to provide the failure details, resulting in the null count for the message.  

One solution could be to store the actual count result inside the matches method for use in the failureDescription to provide the expected behavior.

**Comment by amenning** [comment]
#4271 is a potential solution PR

**Comment by sebastianbergmann** [comment]
Superseded by #4567 and #4568.
