### ISSUE TITLE
Replace "whitelist" for coverage

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/phpunit#4275]
There are better ways to express the notion of whitelisting, without using this outdated, offensive terminology. Currently, has to write something like this, to use this PHPUnit functionality:

```xml
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
```

Can we provide an alternative mechanism and deprecate the original?

// cc @ciaranmcnulty, @leah

**Comment by sebastianbergmann** [comment]
This is already being worked on:

* https://github.com/sebastianbergmann/global-state/commit/8bac4a616ae8b9070f00ccce19eec3aefc4be85b
* https://github.com/sebastianbergmann/php-code-coverage/commit/92cb0536ccf85e90479b066c6a9ead8bbb2d5fb9
* https://github.com/sebastianbergmann/php-code-coverage/commit/7dda60abcb21c251f2730c2fac2a48e2844d368f
* https://github.com/sebastianbergmann/phpunit/commit/71c963cef23bc9426f0fc9dd74259e67edf6dd29
* https://github.com/sebastianbergmann/phpunit/commit/28e1d58a0c5a0b0f62acd37cad807bb539aff353
* https://github.com/sebastianbergmann/phpunit/commit/7b3fdaf8b6e3a38e5078b006bd2143b8ad1ef9b7
* https://github.com/sebastianbergmann/phpunit/commit/b4e0791de785af1ccf3e4d18390f9d505c2a5f1e
* https://github.com/sebastianbergmann/phpunit/commit/8e9c76d33dab4095c9066072076f368193e4166d

I will continue to work on this as fast as I can but I do not need a ticket to track this.

**Comment by jycr753** [comment]
Is not offensive, so please stop with this non sense! STOP.

https://www.reddit.com/r/AskHistorians/comments/866ynp/what_are_the_origins_of_the_words_blacklist_and/

**Comment by GrahamCampbell** [comment]
The historical origins of the word from hundreds of years ago are not relevant. The connotations in the modern word are unacceptable, and that's all that matters.

**Comment by jycr753** [comment]
So we come to this, a white boy to tell what I should be offended by? it is just words and means nothing else that blacklist (in the dark side), whitelist(in the good side)

**Comment by bastianschwarz** [comment]
Since we all know what tends to happen to such "discussions", just a friendly reminder beforehand that https://github.com/sebastianbergmann/phpunit/blob/master/.github/CODE_OF_CONDUCT.md exists.

Everyone just take a deep breath and think about if this is really the battle you want to pick, no matter what side your opinions falls on. It is already being worked on so maybe you shouldn't invest too much energy into this?

**Comment by jycr753** [comment]
@bastianschwarz Thanks for that, I did take a deep breath :) 

There is nothing we can do at the moment since is something already happening, but I wanted to clear out that is not an issue for most of the world and most people do not support this, because programming has nothing to do with race, culture. we are big team and someone has to point out when were are going into odd ways.

**Comment by codemasher** [comment]
Imagine vigorously defending racist terminology. 

https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.2

**Comment by jycr753** [comment]
@codemasher that is based on culture. in my culture it means good and evil, god and devil, nothing to do with race. making changes like this is telling me your culture is better just because reasons?

**Comment by codemasher** [comment]
"I don't feel oppressed by it therefore it's not offensive" is not how it works.

**Comment by jycr753** [comment]
is literally how it is working: "those words oppressed me, remove it"

**Comment by GrahamCampbell** [comment]
To be honest, this isn't really up for discussion. It has already been implemented in v9. I'd recommend @sebastianbergmann locks this thread because further comments are not required.
