### ISSUE TITLE
Remove support for old code coverage configuration

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4279]

**Comment by emodric** [comment]
Hi @sebastianbergmann 

I realize that you have your release process that you tend to stick to, but can these issues with removing support for the old configuration format be postponed for PHPUnit 11? Or, maybe better (since PHPUnit 8 is still actively supported), maybe implement a forward compatibility layer in 8.x to ease the migration?

The practical issue with our project is that PHPUnit 9(.3) does not support PHP 7.2, so we're stuck on PHPUnit 8 when testing on 7.2, which means that we are unable to use the new configuration format, and thus need to maintain two sets of configuration. Multiply this by the sheer number of repositories we have for the project, and things pretty much start to get out of hand. I know that PHP 7.2 will be EOLed soon, but sometimes clients do not care.

Changing the entire configuration format out of the blue without some kind of forward compatibility layer in older versions, or sufficient time to migrate will definitely put strain on the community and efficient use of PHPUnit.

Thanks!

**Comment by sebastianbergmann** [comment]
Forward compatibility will not be added to PHPUnit 8.5. Backward compatibility will be removed in PHPUnit. When this is implemented for PHPUnit 10, the old version will be PHPUnit 9. And PHPUnit 9 is forward compatible.

You should be able to maintain two separate PHPUnit XML configuration files in your repository, one that is compatible with PHPUnit 8.5 and one that is compatible with PHPUnit 9.3 and newer. When you run your tests, be it locally or in your CI pipeline, you use the configuration file appropriate for the PHP version you want to test with.

**Comment by sebastianbergmann** [comment]
Let me try to provide a bit more context.

A team of developers works on a software. That software is deployed in production using a specific version of PHP. The developers -- hopefully -- use the same version of PHP for development that is used in production. The developers use a version of PHPUnit that is compatible with the version of PHP they use. I cannot think of a reason why these developers would want to run their tests with different versions of PHPUnit.

Of course, product development, and here it does not really matter whether closed source or open source, is different from the type of development I described above. If the developers of a product make the decision that they want to support many different versions of PHP in the same codebase then, yes, using PHPUnit for this product is painful. And, of course, I feel bad about this pain that the developers experience. In my opinion, they should rethink their decision to support many different versions of PHP.

"Many different versions of PHP" includes old and unsupported versions as well as current versions. By supporting a version of PHP that is no longer (actively) supported by the PHP project in your product you make it at least seem okay to use outdated versions. It is not, at least not in my opinion.

A team cannot, and should not, update all their dependencies -- including PHP and PHPUnit -- all the time. But once within a timeframe of 1-2 years is not too much to ask if you ask me.

**Comment by emodric** [comment]
I am talking about product development, yes, not client projects. What I meant with "client does not care" is that client wants the new features in our product and still use older versions of PHP on their projects. They have paid for the support, after all, even if the product is open source.

I agree that allowing the use of older versions of PHP is not okay, but the reality is pretty much always different. And yes, I know I can maintain two different versions of `phpunit.xml`, but that's exactly what I am trying to avoid.

On the last point, I do not agree that we should not upgrade our dependencies at soon as time allows. I treat my dependencies as as treat my code. If I don't refactor code when it needs refactoring and update dependencies when I can, they rot and bring more and more problems as the time passes. Not one time I have been bitten with dependency hell because someone somewhere was still using an obsolete version of a package.
