### ISSUE TITLE
can't stub getMessage method of interface that extends Throwable

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [sebastianbergmann/phpunit#4458]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.10
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

`$mock->method('getMessage')` fails for interface that extends `Throwable`

#### Current behavior

`testRealThrowable` fails with error:

> Trying to configure method "getMessage" which cannot be configured because it does not exist, has not been specified, is final, or is static

#### How to reproduce

```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Throwable;

interface Bar extends Throwable
{
    public function foo();
}

interface FakeThrowable
{
    public function getMessage();
}

interface Baz extends FakeThrowable
{
    public function foo();
}

final class FooTest extends TestCase
{
    public function testFakeThrowable(): void
    {
        $mock = $this->createMock(Baz::class);
        $mock->method('foo')->willReturn(null);
        $mock->method('getMessage')->willReturn(null);
        $this->assertTrue(true);
    }

    public function testRealThrowable(): void
    {
        $mock = $this->createMock(Bar::class);
        $mock->method('foo')->willReturn(null);
        $mock->method('getMessage')->willReturn(null);
        $this->assertTrue(true);
    }
}
```

#### Expected behavior

Both tests pass

**Comment by thicolares** [comment]
@jacekkarczmarczyk: it happens because when PHPUnit detects you're mocking an interface that extends `Throwable`, PHPUnit returns an `Exception` mock instead **[1]**. 

But on `Exception`, `getMessage` is `final` therefore you see the error.

**[1]** You may want to [read this thread](https://github.com/sebastianbergmann/phpunit-mock-objects/pull/402) that was created based on [this bug report](https://github.com/sebastianbergmann/phpunit/issues/2995).
