### ISSUE TITLE
Question: how to discover from within a test whether code coverage is being recorded ?

### ISSUE THREAD

**Issue by jrfnl** [sebastianbergmann/phpunit#4680]
### Usecase

I'm doing some convoluted performance testing on a project to safeguard against a nasty performance leak.

Part of the solution is to put a form of caching in place for the performance heavy code and in the test suite I'm doing a comparison of the runtime of the same code without and with the cache to make sure the caching has the desired effect on performance.

### Question

Now, when I run these tests with code coverage turned on, the runtime of the tests will (logically) be quite different.

I've been searching in the source code for a constant or something I can use to tell whether the tests are being run with code coverage turned on, but haven't been able to find anything like that.

So my question is: is there any way I can tell from within a test that the test is being run with code coverage turned on ? (by checking a constant value, property value or in another way)

For my purposes, it would be absolutely amazing if there was a way which worked PHPUnit cross-version as these tests need to run on PHP 5.4 - current.

**Comment by sebastianbergmann** [comment]
No such mechanism exists because a test must be oblivious, IMO, to such things.

That being said, if you collect code coverage using Xdebug then you should be able to use the [xdebug_code_coverage_started()](https://xdebug.org/docs/all_functions#xdebug_code_coverage_started) function to query whether Xdebug is collecting code coverage information. I am not aware of a similar function in PCOV.

**Comment by jrfnl** [comment]
@sebastianbergmann Thanks Sebastian for the suggestion! I'll have a play with it to see if I can make it work that way.
