### ISSUE TITLE
sebastian/resource-operations dependency is abandoned

### ISSUE THREAD

**Issue by andrei-dascalu** [sebastianbergmann/phpunit#4714]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.5
| PHP version         | 7.4.20
| Installation Method | Composer 

#### Summary

`Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.`

`phpunit/phpunit  9.5.5  requires  sebastian/resource-operations (^3.0.3) `

#### Current behavior

Currently package `sebastian/resource-operations` that is abandoned is required by phpunit

#### How to reproduce

Composer install/update will report this issue

#### Expected behavior

Ideally there shouldn't be dependencies on abandoned packages. I'm not entirely sure how this is generally handled within the project, I plan to take a look to see how much of a dependency this is. I will come back on the ticket if I see any straightforward alternatives.

**Comment by sebastianbergmann** [comment]
This is not a bug. `sebastian/resource-operations` will not be changed anymore. PHPUnit 8.5 and PHPUnit 9.5 still depend on it to provide a functionality that nobody really uses (which is the reason why it was removed from PHPUnit 10). Do not worry about it, simply ignore the warning.

**Comment by ruudk** [comment]
@sebastianbergmann Would it be an idea to un-abandon `sebastian/resource-operations` until PHPUnit 10 is released? Everyone that runs `composer install` or `composer outdated` will see this warning.

**Comment by ralfstrobel** [comment]
I concur with @ruudk - asking people to ignore warnings is bad practice. We have a standing guideline not to let library deprecation warnings pile up and treat them as soon as they occur.

For now I have no choice but to manually remove the `"abandoned": true` entry from our composer.lock file each time we update it.

**Comment by Tiththa** [comment]
> I concur with @ruudk - asking people to ignore warnings is bad practice. We have a standing guideline not to let library deprecation warnings pile up and treat them as soon as they occur.
> 
> For now I have no choice but to manually remove the `"abandoned": true` entry from our composer.lock file each time we update it.

can this config option be added if it doesn't exist in my `composer.lock` file ? If so, where would i need to add this `"abandoned":true` option?

**Comment by VARGA-Peter** [comment]
I am running PHP 8.0.8 and phpunit 9.5.7

As @ruudk and @ralfstrobel  already stated it's a very bad practice to suggest to ignore a warning. There should be a better solution.

_My question:_ What can I do in order to get rid of this warning what the _owner_ suggests.

**Comment by ProfessorGram** [comment]
Agree with @ruudk and @ralfstrobel - I have just wasted a bunch of time looking into a warning that apparently "means nothing".  This kind of insouciance is rampant in open-source and a real burden on the community.  Developers should either deliver working code, or excise non-working code, or leave stubs in that *inform* rather than warn.  Also, you may be surprised to find out how many people actually rely on an "unused" module in their production environments.

**Comment by ejimenez123** [comment]
With all due respect, I imagine that the ones who complain so severely are the ones who pay @sebastianbergmann. In the meantime, I can only thank him for putting such a powerful tool in my hands without taking money out of my pocket. I will continue to wait patiently for news.

**Comment by ralfstrobel** [comment]
If the tone of my comment made it seem like I mean to disrespect Sebastian or his work, then I apologize. However, feedback and discussion about best practices is a vital part of open source culture. If nobody every complained about free software, free software wouldn't be as good as it is.

**Comment by VARGA-Peter** [comment]
> With all due respect, I imagine that the ones who complain so severely are the ones who pay @sebastianbergmann. In the meantime, I can only thank him for putting such a powerful tool in my hands without taking money out of my pocket. I will continue to wait patiently for news.

Nobody was complaining about the tool. It was only stated that it's a bad practise to suggest to ignore warnings. And I repeat: It's a very bad practise!

My C++ projects compile without any warning so the other languages do. A warning is a warning and **must not** be ignored. Starting ignoring warnings will lead over the time to bigger problems because the developer become _resistant_ against warnings because they supposedly mean nothing.

And, as @ralfstrobel pointed out: If nobody would "_complain_" about a free software then this free software wouldn't achieve this quality. Nobody was attacking @sebastianbergmann at all - this would be rude, offensive and should be penalised - we only talked about the recommendation to ignore warnings.

**Comment by phaldan** [comment]
Looks like `sebastian/resource-operations` is not abandoned anymore.

**Comment by VARGA-Peter** [comment]
> Looks like `sebastian/resource-operations` is not abandoned anymore.

Yep, I confirm. Very nice. No warnings at all! Thank you!

**Comment by erikn69** [comment]
Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.

**Comment by drealecs** [comment]
Maybe if there would be a way for composer packages to be in security-only maintenance mode or development-freeze mode, we would have a nicer message that could better clarify the intent here and would be easily ignored by users.
"abandoned" sounds a bit too harsh, 😄.

**Comment by luisburgosvilca** [comment]
> > Parece que `sebastian/resource-operations`ya no está abandonado.
> 
> Sí, lo confirmo. Muy agradable. ¡Sin advertencias en absoluto! ¡Gracias!

¿cómo lo hicieron? me sigue saliedo el warning
