### ISSUE TITLE
PHP 8.1-beta1 causes fatal error when running from Phar

### ISSUE THREAD

**Issue by jrfnl** [sebastianbergmann/phpunit#4740]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.7
| PHP version         | 8.1.0-beta1
| Installation Method | PHAR

#### Summary

When I try to run any test suite on PHP 8.1.0-beta1 using the PHPUnit phar, it results in:

```
PHP 8.1.0beta1 (cli) (built: Jul 20 2021 17:20:01) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.0-dev, Copyright (c) Zend Technologies

Fatal error: Could not check compatibility between PHPUnit\PharIo\Manifest\AuthorCollection::getIterator(): PHPUnit\PharIo\Manifest\AuthorCollectionIterator and IteratorAggregate::getIterator(): Traversable, because class PHPUnit\PharIo\Manifest\AuthorCollectionIterator is not available in phar://phars/phpunit-9.5.7.phar/phar-io-manifest/values/AuthorCollection.php on line 33
```

#### Current behavior

I tested with the same PHPUnit/PHP combination against various test suites. All resulted in the above error. No tests are run.

#### How to reproduce

* Download the PHPUnit phar.
* Place it somewhere where it is within the system path.
* Run it from the root directory of any project which has tests, like the root directory of the PHPUnit repo ;-)

#### Expected behavior

For the tests to run 😉

**Comment by jrfnl** [comment]
Note: I've opened this issue here as the error notice indicates it is a problem with the Phar missing a file.

**Comment by sebastianbergmann** [comment]
The PHAR for PHPUnit 9.5.7 was built with `phar-io/manifest` 2.0.1. Since then, [version 2.0.3](https://github.com/phar-io/manifest/compare/2.0.1...2.0.3) of that library has been released which contains a fix for the PHP 8.1 deprecation notices.

As you can see [here](https://github.com/sebastianbergmann/phpunit/runs/3113624978), the PHAR built from the current state of `9.5` fails for a different (but similar) reason that I shall address shortly.

Thank you for bringing this to my attention. We [now](https://github.com/sebastianbergmann/phpunit/commit/77f68f12766a6750694a2636eafa0398f4a585da) test the PHAR against all supported versions of PHP instead of just one.

**Comment by sebastianbergmann** [comment]
> The PHAR for PHPUnit 9.5.7 was built with `phar-io/manifest` 2.0.1. Since then, [version 2.0.3](https://github.com/phar-io/manifest/compare/2.0.1...2.0.3) of that library has been released which contains a fix for the PHP 8.1 deprecation notices.

Oh-kay, this more complex than originally thought. The deprecation notices are fixed in `phar-io/manifest` 2.0.3, but PHPAB's topological sort of code units puts the import of `AuthorCollection` before `AuthorCollectionIterator` leading to

```php
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollection.php';
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollectionIterator.php';
```

which results in

```
Fatal error: Could not check compatibility between
PharIo\Manifest\AuthorCollection::getIterator(): PharIo\Manifest\AuthorCollectionIterator
and IteratorAggregate::getIterator(): Traversable, because class
PharIo\Manifest\AuthorCollectionIterator is not available in /path/to/manifest/src/values/AuthorCollection.php on line 31
```

Changing

```php
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollection.php';
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollectionIterator.php';
```

to

```php
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollectionIterator.php';
require __DIR__ . '/../vendor/phar-io/manifest/src/values/AuthorCollection.php';
```

fixes this.

However, this certainly will break at some point in the future when additional compile-time checks are added to PHP. The only solution I see is to stop using a static autoloader for the PHAR. This was required in the past for preventing errors in environments where users run PHPUnit from a PHAR in a project where (a different version of) PHPUnit is also installed using Composer. This was before we had scoped PHARs.

Regarding the topological sorting of code units performed by PHPAB: that is a different topic (for a different repository). I suspect that PHPAB's sorter does not look at return type declarations (yet) as it should have otherwise detected the cyclic dependency between `AuthorCollection` before `AuthorCollectionIterator`.

**Comment by sebastianbergmann** [comment]
@nikic **ping** to let you know that these recent changes in PHP 8.1 caused an issues that was unexpected, at least to me. Maybe this should be noted in the upgrading notes?

**Comment by sebastianbergmann** [comment]
Current status: PHARs built from `8.5`, `9.5`, and `master` work on PHP 8.1. However, building the PHAR using PHP 8.1 does not work. This is what causes the build failures [here](https://github.com/sebastianbergmann/phpunit/runs/3131198170) and [here](https://github.com/sebastianbergmann/phpunit/runs/3131198059).

**Comment by jrfnl** [comment]
Thanks @sebastianbergmann for your swift action on this and the detailed analysis.

I'd seen the PHP 8.1 update commits in Phar.io before I opened this issue, but as they didn't seem to involve the classes mentioned in the error, I had a feeling this was going to be more complex than just updating.

**Comment by sebastianbergmann** [comment]
I have raised a [question](https://news-web.php.net/php.internals/115549) about this on the PHP development mailinglist.

**Comment by jrfnl** [comment]
Setting `error_reporting` to `-1` for the Phar build test runs showed me two more PHP 8.1 issues. Reported in: https://github.com/box-project/box/pull/557

**Comment by sebastianbergmann** [comment]
As of d7258e09402f83e87fb0caa6f16f8e1da91ee8cb, PHPUnit now errors out when it detects that it was invoked from a PHAR but its code is autoloaded from a different source such as a Composer-managed installation.
