### ISSUE TITLE
Getting blank and no process after updating 9.5.11 version

### ISSUE THREAD

**Issue by creativedevs** [sebastianbergmann/phpunit#4863]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.11
| PHP version         | 7.3
| Installation Method | Composer

#### Summary

Getting blank screens after executing below command

$ ./vendor/bin/phpunit
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

testcase are not running

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by creativedevs** [comment]
@sebastianbergmann Can we connect over zoom or slack to show you issue? 

I am just getting blank, no execution since 6-7 days.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by creativedevs** [comment]
When use refershDatabase in testcase, it starts to give blank. see attached screenshot


![phpunit-issue](https://user-images.githubusercontent.com/5255532/149981719-235b5e97-f0fd-4677-ae43-deedb4e707ea.png)

**Comment by sebastianbergmann** [comment]
I do not know what `refershDatabase` is. It is not provided by PHPUnit.

**Comment by 13rAXwNNnaAuCJA3z1REfJbJNMwgK4LBTC** [comment]
bc1qyx68jn9qpl3gug5wfyfd5lrz2cply0ce7dm4f

1 Introduction
The primary function of public cryptocurrency networks, such as Bitcoin, is to maintain a decentralized electronic ledger of transactions. Crucially, this requires that there be no single authority, such as a bank, controlling or validating the contents
Figure 1: oPoW Silicon Photonic Miner Prototype
of the ledger. A naive design of this kind of network may be achieved if users post their transactions publicly via signed messages (using public-key cryptography), and a transaction is considered complete only when the majority of nodes on the network have accepted it. However, if the network is to be trustless/permissionless and resilient to malicious actors, a mechanism must exist to prevent Sybil attacks1 and double- spending2 .
Although there were past attempts at e-cash systems, Bitcoin’s architecture (outlined in the original Nakamoto whitepaper [1]) was the first to solve the double-spend and Sybil attack problems through clever use of Hashcash [2] Proof of Work (PoW). Nakamoto’s key insight was that Proofs of Work enable distributed systems to automatically impose trivially verifiable costs on participating nodes, allowing for byzantine agreement [3] in settings previously believed to be
1Multiple nodes controlled by one malicious actor
2Making two purchases with the same coin by rewriting the ledger to remove the first transaction

Hashrate Growth and Resilience in a Low-OPEX PoW
Shifting mining cost from OPEX to CAPEX, increases the total effective investment made by the network (via block rewards and transaction fees) into long term security. Any OPEX costs the miners incur do not contribute to the hashrate growth and, therefore, do not contribute to the long term secu- rity either. As more funds flow to CAPEX, the network builds up a larger and larger cache of specialized security hardware, making the barrier for attack higher. In a related positive effect of CAPEX dominance, miners running low-OPEX hardware have less incentive to turn it off when the coin price (and therefore mining reward value), or the price of electricity fluc- tuates. Bitcoin’s hashrate growth is not nearly as impressive as it looks when hardware performance improvements are accounted for. Analyzing something like Specific Hashrate (we can loosely define Specific Hashrate as hashrate divided by the dollar cost of performing a single hash) shows that Bitcoin’s security is very sensitive to price. In Q4 2018, Bit- coin prices were volatile, and the coin temporarily lost around 45% of its market value. As a result of miners shutting off their machines to avoid paying for electricity, the hashrate dropped from 60 EH/s to 35 EH/s [52] (despite Bitmain re- leasing a new high performance 7nm miner [53] and other hardware manufacturers joining the fray). oPoW’s economics can create a faster-growing, more stable, and more committed community of miners.
3 Modifying Hashcash
In this section, we show that a simple modification to the hash function at the core of the Hashcash proof of work system, can increase the cost of producing a proof of work.
26Likely the OPEX is closer to a third the relative mining reward so that a miner’s ROI is within a reasonable timeframe.
27 Note that in some cases energy cost could be partially CAPEX rather than fully OPEX if the miner is actually investing in infrastructure. Certainly this is better in terms of hashrate stability as long as the infrastructure cannot be re-purposed, however energy infrastructure is bulky and immobile compared to computing hardware and requires more upkeep.
