### ISSUE TITLE
Cannot change read-only property in the mock

### ISSUE THREAD

**Issue by jakubthedeveloper** [sebastianbergmann/phpunit#4866]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.11
| PHP version         | 8.1.1
| Installation Method | Composer

#### Summary

When trying to set a value for a read-only property in a mocked class, I get the error "Error: Cannot initialize read-only property TestedClass::$testedProperty from scope MockingTest".

#### Current behavior

Error: Cannot initialize readonly property TestedClass::$testedProperty from scope MockingTest

#### How to reproduce

```php
<?php

class TestedClass {
    public function __construct(
        public readonly string $testedProperty
    ) {

    }
}

class MockingTest extends \PHPUnit\Framework\TestCase
{
    public function testCanMockReadonlyProperty()
    {
        $mock = $this->createMock(TestedClass::class);
        $mock->testedProperty = "New value"; // Error: Cannot initialize readonly property TestedClass::$testedProperty from scope MockingTest

        $this->assertEquals("New value", $mock->testedProperty);
    }
}

```

#### Expected behavior

I should be able to change the value of the read-only property when the class is mocked and after the change, the property should be read-only, so I think we should have a method like `setReadOnlyPropertyValue(string $property, mixed $value): void` and setting by $mock->property should still be impossible.

Example:

```php
    public function testCanMockReadonlyProperty()
    {
        $mock = $this->createMock(TestedClass::class);
        $mock->setReadOnlyPropertyValue('testedProperty', 'New value');

        $this->assertEquals("New value", $mock->testedProperty);
    }
```

Another idea is to mock property calls the same way as method calls are mocked:

```php
$mock->expects($this->any())->property('testedProperty')->willReturn('New value');
```

**Comment by sebastianbergmann** [comment]
> I should be able to change the value of the read-only property

You cannot, and you should not.

**Comment by jakubthedeveloper** [comment]
But if I don't set the value I get error if some method that uses the mock tries to access the property, "Typed property must not be accessed before initialization".

**Comment by CSeifert87** [comment]
@sebastianbergmann I also need to ask how we then should test any classes that use simple DTOs or Value Objects?

Example:

`
<?php

class DtoConsumer
{
    public function __construct(private SomeDto $someDto)
    {
    }

    public function getName(): string
    {
        if ($this->someDto->dataOne->isTrue()) {
            return 'a';
        }

        return 'b';
    }
}

class SomeDto
{
    public function __construct(
        public readonly DataOne $dataOne,
        public readonly DataTwo $dataTwo,
    ) {
    }
}
`

Normally I would have something like a `getDataOne()` method on `SomeDto` which I would and could mock. But now with the public readonly properties this is no longer possible. 

This would mean, that we could not get rid of the getters and would still need to inflate our code although for such simple classes it would not be necessary. What would be the (proper) solution for this problem?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by CSeifert87** [comment]
Granted. Then maybe you can elaborate here please? https://stackoverflow.com/questions/72409868/how-to-mock-work-with-public-readonly-properties-in-unit-tests

**Comment by hemberger** [comment]
I recently changed a lot of code to use public readonly properties instead of private properties with public getter methods. This was the main use-case example in Nikita's RFC for readonly properties (https://wiki.php.net/rfc/readonly_properties_v2#introduction), and is a very effective way to remove pointless boilerplate code.

With my old design, I could simply mock the getter method to effectively mock the property. However, since PHPUnit does not support mocking readonly properties, the new design is not testable, even though it is serving an identical purpose.

I understand that PHP is very strict about setting readonly properties, which makes it difficult (if not impossible) to mock them, but it is unfortunate that readonly properties are incompatible with mocking. I wonder, if PHP's reflection library had a way to alter the readonly status -- in the same way that we can alter visibility -- would it then make sense to have a mock method to change a readonly property by temporarily making it non-readonly?
