### ISSUE TITLE
Mocking \ReflectionClass throws an error in PHPUnit 8.5 when run with PHP>=8.1

### ISSUE THREAD

**Issue by m-vo** [sebastianbergmann/phpunit#4879]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5
| PHP version         | 8.1
| Installation Method | Composer

#### Summary
Mocking `\ReflectionClass` throws an error in PHPUnit 8.5 when run with PHP>=8.1.

#### Current behavior
Throws an exception: `Call to undefined method ReflectionUnionType::getName()`.

#### How to reproduce
```php
// Execute with PHP>=8.1
$this->createMock(\ReflectionClass::class);
```

#### Expected behavior
Works like in PHPUnit 9.3.

**Comment by sebastianbergmann** [comment]
Life Support means that changes will be made for an otherwise unsupported version of PHPUnit to be compatible with new versions of PHP. Life Support ends when an old version of PHPUnit cannot be made compatible with a new version of PHP without breaking backwards compatibility.

The fact that a version of PHPUnit supports a specific PHP version means that this version of PHPUnit works on that PHP version for PHP code that is compatible with the version of PHP required by the PHPUnit version in question. For example, PHPUnit 8.5 requires PHP 7.2. PHPUnit 8.5 works for PHP code compatible with PHP 7.2 on PHP 8. However, PHPUnit 8.5's test double code generator does not support PHP 8's union types syntax, for example.

**Comment by sebastianbergmann** [comment]
While it is not a good idea to double classes such as `ReflectionClass`, this should probably be fixed. However, adapting PHPUnit 8.5 for arcance use cases such as this to changes in PHP 8.1 is not very high on my list of priorities. I will, of course, gladly consider a pull request that addresses this.

**Comment by wilsonge** [comment]
@sebastianbergmann happy to do the pull request (we're needing to support this same thing for some failing php 8.1 unit tests in @joomla - due to some slightly suspect mocks we're doing of XMLReader on our end) - done a first part to the type repo at https://github.com/sebastianbergmann/type/pull/24 and then can pick that up in this repo as a part two if accepted.

**Comment by sebastianbergmann** [comment]
I have explained in https://github.com/sebastianbergmann/type/pull/24#issuecomment-1159617882 why support for union types and intersection types will not be backported to PHPUnit 8.5.

If this issue cannot be fixed without a backport of union types and intersection types then this issue will not be fixed. Internal classes such as `ReflectionClass` or `XMLReader` should not be doubled anyway.

**Comment by wilsonge** [comment]
The description you gave there is something you literally crossed out in this issue - so a touch disappointing. But no worries. I guess this entire issue can be closed in that case?

**Comment by sebastianbergmann** [comment]
> The description you gave there is something you literally crossed out in this issue - so a touch disappointing.

I am sorry that you are disappointed. What I meant with

> While it is not a good idea to double classes such as ReflectionClass, this should probably be fixed.

back in https://github.com/sebastianbergmann/phpunit/issues/4879#issuecomment-1027961458 is that I think that PHPUnit 8.5's test double code generator should be adapted to cope with the change made in PHP 8.1 *if that is possible without breaking BC in PHPUnit itself and in the related [library](https://github.com/sebastianbergmann/type).

And because I strongly believe doubling built-in classes (or any type that you do not own) is a bad idea, I will not work on exploring whether this is possible myself.

**Comment by andypost** [comment]
Using PHP 8.2alpha3 with Drupal I'm getting lots of errors in tests because of access to undefined properties, the workaround is to allow `#[\AllowDynamicProperties]` annotation to mocks but I see no method/way to apply this attribute to classes

ref https://wiki.php.net/rfc/deprecate_dynamic_properties

**Comment by sebastianbergmann** [comment]
No feedback, closing.
