### ISSUE TITLE
Warn if a dataprovider returns duplicates

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#5039]
If a data provider method uses complex logic and loops to build up its array of datasets, then it can be easy to accidentally create duplicate sets.

The presence of duplicate sets wastes developer time when running tests, CI time, and energy.

It would be nice if PHPUnit checked for duplicate sets and produced a warning.

**Comment by theofidry** [comment]
It might be worth clarifying what "duplicate" means in this context.

If you mean "there is a duplicate key", then as detailed in #4884, one gets silently removed which is a problem and at the moment you can only circumvent that by creating another data provider combining the ones you desire.

If you otherwise mean duplicate entries, I think this could get both complicated and expansive: comparing data sets is not trivial especially when they can be composed of pretty much anything.

A last known problem is the data being created several times. You can find examples in Infection where the provider is extracted into a dedicated class to memoize the data: https://github.com/infection/infection/blob/master/tests/phpunit/Mutator/MutatorFixturesProvider.php.

I don't know how much PHPUnit could do there. It feels dangerous to just memoize systematically since the user can do _anything_ in a provider, including mutating data which could lead to very unexpected and sneaky issues. On the other hand, not doing anything only leads to this IMO quite verbose solution. Maybe there could be a helper method/function to make it easier to memoize the result. For example:

```php
#[Memoizable] 
public static function fooProvider(): iterable {
    // ...
}
```

**Comment by joachim-n** [comment]
> If you otherwise mean duplicate entries, I think this could get both complicated and expansive: comparing data sets is not trivial especially when they can be composed of pretty much anything.

I meant duplicate entries, but couldn't this be done by hashing the values of the data array and comparing the hashes?

**Comment by sebastianbergmann** [comment]
PHPUnit 10 [triggers an error for data providers that provide duplicate keys](https://github.com/sebastianbergmann/phpunit/blob/230db527c9721424af3a8d611917b59f64a7f36f/tests/end-to-end/event/data-provider-duplicate-key.phpt). I do not think that PHPUnit should look for / act on duplicate values.
