### ISSUE TITLE
assertSame broken after 9.5.14 version

### ISSUE THREAD

**Issue by pablorsk** [sebastianbergmann/phpunit#5045]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.14
| PHP version         | 8.1.10
| Installation Method | Composer

#### Summary

Assuming the following test:

```php
public function testAssertSame()
{
    static::assertSame(40.7, 40.8-0.1);
}
```
In version 9.5.13 this test works perfect:

```
.                                                                   1 / 1 (100%)
```

But, in version 9.5.14, it breaks

```
1) SomeTest::testAssertSame
Failed asserting that 40.699999999999996 is identical to 40.7.
```

Any ideas? I try to set `serialize_precision = 16`, but the problem continued.

**Comment by sebastianbergmann** [comment]
CC @marijnvanwezel @mvorisek

**Comment by sebastianbergmann** [comment]
This may be fixed by https://github.com/sebastianbergmann/phpunit/pull/4972.

**Comment by mvorisek** [comment]
`assertSame` pass only if the values are strictly the same, in your case, the values are not the same, you need to compare them with a small delta using `assertEqualsWithDelta`

**Comment by bancer** [comment]
@sebastianbergmann https://github.com/sebastianbergmann/phpunit/pull/4972 did not fix the problem:

![Screenshot from 2022-12-09 16-39-16](https://user-images.githubusercontent.com/3830106/206738410-6d2a477b-f372-432f-b2ae-1493d16eb5fc.png)

**Comment by mvorisek** [comment]
@bancer please provide a repro case and please keep in mind changes across several phpunit packages were needed, thus please update all packages in your project first

**Comment by mvorisek** [comment]
@bancer the assertion is correctly not met - https://3v4l.org/5CiYa

**Comment by bancer** [comment]
> @bancer the assertion is correctly not met - https://3v4l.org/5CiYa

Well, everybody could assume that 40.7 is mathematically the same value as 40.8-0.1.

**Comment by mvorisek** [comment]
you can use `$delta` in `assertEquals`, `assertSame` check for 1:1 binary value

**Comment by anders-photowall** [comment]
I ran in to this problem today after doing what is supposed to be a safe composer update since we have caret notation and minor and patch updates should never have breaking changes. This very much is a breaking change and on a _patch_ version which I think is extremely surprising. Was this an unintended and unknown breaking change? Or should the phpunit lib be considered unsafe and potentially breaking to update even _patch_ changes on? That should be very clearly stated in the documentation in that case.

**Comment by marijnvanwezel** [comment]
I think that strictly speaking, the change could be considered a patch only. The previous behaviour (<= 9.5.13) was incorrect, as an assertion could pass even if it clearly shouldn't have. Comparisons between floats should not be done with `assertSame`, but it might be good to more clearly mention this in the documentation.

That being said, since many people relied on this incorrect behaviour, including it in a major release might have been a better approach.
