### ISSUE TITLE
Deprecate withConsecutive()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5063]
`withConsecutive()` has been [removed](https://github.com/sebastianbergmann/phpunit/issues/4564) in PHPUnit 10.

**Comment by oleg-andreyev** [comment]
workaround: https://gist.github.com/oleg-andreyev/85c74dbf022237b03825c7e9f4439303

**Comment by TomasVotruba** [comment]
There are around ~10 variations of how PHPUnit `withConsecutive()` can be upgraded. If there is a reference, followed by `willReturn*()` or by `willReturnOnConsecutive()` and more.

Instead of creating answer that fits only one specific quesition, I've put down an article that explains, how to upgrade all kind of combinations.

See:
https://tomasvotruba.com/blog/how-to-upgrade-deprecated-phpunit-with-consecutive

Hopefully you'll find it useful.

It includes PHP 7.* ready code (no `match`), that can be used in PHPUnit 9 (that requires 7.3+)

**Comment by PavelLoparev** [comment]
phpunit degrades fast
