### ISSUE TITLE
Assert that arrays (or objects) are equal while excluding certain keys (or properties)

### ISSUE THREAD

**Issue by NolwennD** [sebastianbergmann/phpunit#5108]
Some object may have properties with unpredictable values, like random UUID, and you want to compare the predictable ones.

In Java, with AssertJ it’s possible with: `assertThat(actual).usingRecursiveComparison().ignoringFields("id").isEqualTo(expected)`.

Maybe a signature like `assertEqualsIgnoringFields($expected, $actual, string ...$fields)`

```php
<?php

class Foo {

    private readonly DateTimeImmutable $date;
    public function __construct(private readonly string $name)
    {
        $this->date = new DateTimeImmutable();
    }
}

/**
* @test
*/
public function passingTest(): void
{
    $foo1 = new Foo("fooName");
    $foo2 = new Foo("fooName");

    self::assertEqualsIgnoringFields($foo1, $foo2, "date");
}
```

**Comment by sebastianbergmann** [comment]
My suggestion would be to implement `Foo::equals()` and then use `assertObjectEquals()`.

**Comment by lolli42** [comment]
This can be done with a custom comparator, if I understand the issue correctly.
They are surprisingly simple to implement, see
https://stackoverflow.com/questions/43589561/phpunit-getting-equalto-assertion-to-ignore-property
for an example that worked for me.

**Comment by sebastianbergmann** [comment]
@lolli42 You are correct. I am still undecided whether or not I want to implement this or not (and recommend using a custom comparator instead).

**Comment by gnutix** [comment]
I have quite a complex immutable value object representing a time interval (like `2023-09-19T16:43:12/2023-09-19T23:59`). Some of the methods (`isEmpty`, `getInclusiveEnd`, etc) have quite an impact on performances if they are called a big number of times. So I thought: easy, let's add a private property that acts as a cache for these values (as they can never change for a given instance of the object), and they'll be computed only once on demand.

What I did not expect was that now most of my unit tests are broken, because we compare objects (and array of objects) quite a lot, and now sometimes these cache properties will be set, and sometimes they wont (depending on whether or not the method was called at least once before the comparison). Which is then seen as a difference by `assertEquals`/`assertSame` : 

```diff
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
             0 => Gammadia\DateTimeExtra\LocalDateTimeInterval Object (
                 'start' => Brick\DateTime\LocalDateTime Object (...)
                 'end' => Brick\DateTime\LocalDateTime Object (...)
-                'isEmpty' => false
             )
             1 => 1
         )
     )
 )
```

@sebastianbergmann  Is there a way to tell PHPUnit to **globally** (aka not by registering some custom comparator in each test) ignore these cache-related private properties when doing comparisons ? Something like the `#[Exclude]` PHP attribute in Symfony Serializer or such ?

**Comment by gnutix** [comment]
Thanks for your answer. I went the `assertObjectEquals` road. I had to add a quite weird implementation to `equals` on another object that uses `LocalDateTimeInterval` internally, but otherwise it went okay and works.

**Comment by sebastianbergmann** [comment]
The use case "assert that arrays are equal while excluding certain keys" has since been implemented:

- `assertArrayIsEqualToArrayOnlyConsideringListOfKeys()`
- `assertArrayIsEqualToArrayIgnoringListOfKeys()`
- `assertArrayIsIdenticalToArrayOnlyConsideringListOfKeys()`
- `assertArrayIsIdenticalToArrayIgnoringListOfKeys()`

I do not think that we need to add similar assertions for objects as custom comparators and `assertObjectEquals()` sufficiently address that use case.
