### ISSUE TITLE
Repeating tests

### ISSUE THREAD

**Issue by tanerkay** [sebastianbergmann/phpunit#5174]
Now that the `--repeat` option has been removed as of phpunit 10, I'm wondering if this feature is planned to be implemented in another way?

I tried without success to find any discussion regarding this change, and an curious as to why it has been removed. Is the onus on test runners or IDEs to provide the repeat functionality going forward? Or is the idea that developers should not be relying on the need for repeating tests?

Context: my use case for repeating tests is often when random data is involved, or in imperfect test suites where tests are not run in isolation, and database or application state between tests affects results. It helps identify, debug and improve these flaky tests.

**Comment by sebastianbergmann** [comment]
> Now that the `--repeat` option has been removed as of phpunit 10, I'm wondering if this feature is planned to be implemented in another way?

Bringing back this functionality is not planned.

**Comment by BinaryKitten** [comment]
@sebastianbergmann - I appreciate that the feature has been removed and isn't being planned to be brought back.

Is there any documentation around the decision for it's removal? - so far we've found the commit that removes it but would love to understand the root cause and where it came from so any further information as to the change would be highly desirable and welcomed.

**Comment by sebastianbergmann** [comment]
> Is there any documentation around the decision for it's removal?

Unfortunately not, sorry.

**Comment by BinaryKitten** [comment]
Thank you anyway.

Appreciate the response as always.

**Comment by evgeek** [comment]
I sincerely hope that this functionality will return over time, because it is incredibly useful. In some cases, a test might only succeed 99% of the time, and `--retry` helped find the reasons why the remaining 1% of runs didn't work.

Maybe someone will be interested in the workaround I use:

```php
trait MultipleRuns
{
    public function multipleRuns(): array
    {
        $result = [];
        for ($i = 0; $i < self::RUNS; $i++) {
            $result[] = [];
        }
        return $result;
    }
}
```

In test class:
1. `use MultipleRuns;` 
2. `protected const RUNS = X;` (X for number of retries)
3. `@dataProvider multipleRuns` in the phpdocs of the repeatable test

**Comment by sanmai** [comment]
As a workaround, consider using a shell loop:
```bash
while php vendor/bin/phpunit tests/ExampleTEst.php --stop-on-failure; do echo; done
```

**Comment by lphilps** [comment]
Very sad.  I used this option all the time.  I'm really going to miss it!

**Comment by lphilps** [comment]
@sebastianbergmann Could I respectfully ask you to re-consider the removal of this option?  Now that it is is gone I have been made very aware of how often I used it, and how incredibly useful it was. It made debugging tests that failed very rarely so easy. There are workarounds but they are kludgy.  And often for me running a single test with --repeat 100 for example, and looking at the percentage of test failure was key clue as to the source of the problem - and I have not found a workaround for that yet.

**Comment by paulpreibisch** [comment]
I am also not happy about this - Here is the workaround in PhpStorm:
Edit configuration settings

In the interpreter options:
--repeat=100

**Comment by mikebronner** [comment]
Agreed, we used repeat all the time to weed out edge cases on tests with randomized data.

**Comment by AJenbo** [comment]
Really sad to see this go as it was one of the more useful options 😔

**Comment by Nutickets** [comment]
Feeling the burn without this feature 🤕 It's a life saver for those gnarly 'only fail some of the time' tests.

**Comment by Rogierownage** [comment]
I, too, would like this feature returned, please.

**Comment by nozkok** [comment]
I can't comprehend why such a functional feature has been removed.

I've created two aliases for my case, and I wanted to share them with you as well.


```
alias rt='repeat_php_test'

repeat_php_test() {
  while true; do
    command_to_repeat="php artisan test $1"
    eval "$command_to_repeat"
  done
}

alias rtf='repeat_php_test_with_filter'

repeat_php_test_with_filter() {
  while true; do
    command_to_repeat="php artisan test --filter $1"
    eval "$command_to_repeat"
  done
}

```

You can add these aliases to your `~/.bashrc` file.
Then you can use  it just typing like this examples:

For all tests:  `rt` 
Some tests: `rt tests/ExampleTest.php` 
Filtered tests:  `rtf someFilterKey`

**Comment by arthurshafikov** [comment]
This was a useful feature to test out unstable test cases. I personally have found and fixed a lot of unstable tests with this. It has to be returned IMO.

**Comment by brianwozeniak** [comment]
Same for my team as well. We have thousands and thousands of tests and once in a blue moon a test fails, but then subsequently passes again. We typically used the `--repeat` option to help diagnose these sort of tests by running than hundreds of times to figure out if it is indeed a randomly failing test which lets us narrow in on the problem so that it can be addressed. Often times this will be used in conjunction with a debugger as well only triggering the breakpoint where it reaches the failed position. Very helpful for us.

Everyone I have talked to does not understand the decision to remove the feature, it was great to have for diagnosing, debugging, and resolving flaky tests that need to be improved.

**Comment by jrfnl** [comment]
Heads up: #5718
