### ISSUE TITLE
Expectations on mock objects aren't counted as an assertions anymore

### ISSUE THREAD

**Issue by Schleuse** [sebastianbergmann/phpunit#5180]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.5
| PHP version         | 8.1.2
| Installation Method | Composer

#### Summary

Expectations on mock objects aren't counted as an assertions anymore. This worked fine under PHPUnit 9 but not with PHPUnit 10.

#### Current behavior

Tests that do not perform any assertions but are using expectations on mock objects are treated as risky tests which is not correct. 

> This test did not perform any assertions

#### How to reproduce

**Test:**
```php
$stub = $this->createStub(\Countable::class);
$stub->expects($this->once())
  ->method('count');
$stub->count();
```
This should count as a valid test.

#### Expected behavior

As described in the [documentation](https://phpunit.readthedocs.io/en/10.0/risky-tests.html#useless-tests), expectations on stub objects should count as assertions.

> A test that does not perform an assertion will be marked as risky when this check is enabled. Expectations on mock objects count as an assertion.

**Comment by sebastianbergmann** [comment]
Expectations on mock objects count as an assertion, but you are using a test stub (not a mock object):

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

interface I
{
    public function m(): void;
}

final class TestDoubleTest extends TestCase
{
    public function testStub(): void
    {
        $i = $this->createStub(I::class);
        
        $i->expects($this->once())
          ->method('m');
        
        $i->m();
    }

    public function testMock(): void
    {
        $i = $this->createMock(I::class);
        
        $i->expects($this->once())
          ->method('m');
        
        $i->m();
    }
}
```
```
PHPUnit 10.0.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.2

R.                                                                  2 / 2 (100%)

Time: 00:00.093, Memory: 8.00 MB

There was 1 risky test:

1) TestDoubleTest::testStub
This test did not perform any assertions

/home/sb/TestDoubleTest.php:11

OK, but some tests have issues!
Tests: 2, Assertions: 1, Risky: 1.
```

If you need a mock object then use `createMock()` to create it. For legacy reasons, `createMock()` and `createStub()` both return an object that technically is a mock object. But the object created (and returned) is only treated as a mock object when you use `createMock()`.

Ever since `createStub()` was introduced, the documentation said to use `createStub()` when you want a test stub and to use `createMock()` when you want a mock object. As a side effect of cleanup work done for PHPUnit 10, a "mock object" created using `createStub()` will no longer be treated as a mock object.

**Comment by Schleuse** [comment]
@sebastianbergmann Thank you very much for explanation! :+1:
