### ISSUE TITLE
PHPUnit 9.6 misses deprecation warning for `withConsecutive()` removed in PHPUnit 10

### ISSUE THREAD

**Issue by SimonFrings** [sebastianbergmann/phpunit#5182]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.3
| PHP version         | 8.1, 8.2
| Installation Method | Composer

#### Summary

We read about the changes in PHPUnit 10 and the removal of `withConsecutive()` + its alternatives (https://github.com/sebastianbergmann/phpunit/issues/4564 and https://github.com/sebastianbergmann/phpunit/issues/4026), so starting with a  smooth upgrade path for our projects by upgrading to PHPUnit 9.6 first seemed like a logical step. We expected to see deprecation warnings for `withConsecutive()`, as they have been deprecated in https://github.com/sebastianbergmann/phpunit/issues/5063. After running the test suite with 9.6.3, there was no output to inform us about any deprecation, so it seems to me that there are no warnings for this method implemented yet, but I think there should be.

I'm interested in your thoughts on this. 

Btw, thanks for all the work you put into PHPUnit  :+1:

**Comment by sebastianbergmann** [comment]
Adding `@deprecated` to the method declaration of `withConsecutive()` unfortunately is the only thing that we can do here due to the way the internals of PHPUnit 9 work.

In PHPUnit 10 we would simply trigger an event ("test used deprecated PHPUnit feature"), but in PHPUnit 9 we simply do not have a way to report deprecations in the test double system.

**Comment by oleg-andreyev** [comment]
workaround: https://gist.github.com/oleg-andreyev/85c74dbf022237b03825c7e9f4439303
