### ISSUE TITLE
Allow excluding warnings on the usage of deprecated symbols

### ISSUE THREAD

**Issue by acelaya** [sebastianbergmann/phpunit#5191]
After updating to PHPUnit 10, I have noticed it prints some warnings when tests are using symbols marked as deprecated.

While I think this might be useful when it comes to third party code (although I'm not sure if PHPUnit is the kind of tool that should highlight this, and it might fall more into the static analysis world, but that's a different story), it is a bit inconvenient when it complains about deprecated symbols from the project itself.

I have a couple of deprecated things that I intend to remove on the next major version, but while they are in the project, I also want to keep their tests around. When I remove these, I will remove their tests as well.

And I know this is not making the tests fail in any way, but it can distract you from actual warnings that should be addressed.

Because of this, it would be great to be able to either disable this check entirely (making it behave as PHPUnit 9), or disable it for certain namespaces/paths.

**Comment by sebastianbergmann** [comment]
The only thing you see by default is that the progress printer prints `D` instead of `.` for a successful test. Does this alone already distract you?

If you use the `--display-deprecations` CLI option or set `displayDetailsOnTestsThatTriggerDeprecations="true"` in your XML configuration file then you see details about deprecations.

Internally, PHPUnit already collects `E_DEPRECATED` (something in PHP is deprecated), `E_USER_DEPRECATED` (triggered using `trigger_error()` in PHP code to indicate that something is deprecated), and deprecations for "something is deprecated in PHPUnit" separate from each other.

Using `--display-deprecations` or `displayDetailsOnTestsThatTriggerDeprecations="true"` is all or nothing right now: when used, PHPUnit will show details about all deprecations in PHP and in PHP code. Details for deprecations triggered by PHPUnit itself are always displayed.

That being said, I agree that the current situation can be improved.

We could, for instance, group deprecations by message in the detailed output.

We should also explore what you propose and optionally limit the display of deprecations to those deprecations that are triggered in your code.

**Comment by acelaya** [comment]
> The only thing you see by default is that the progress printer prints D instead of . for a successful test.

Yes, sorry. I didn't mean it printed the whole message.

> Does this alone already distract you?

Yes, because if at some point there's a new warning I should actually pay attention to, I won't notice.

**Comment by VincentLanglet** [comment]
@sebastianbergmann I encountered a similar issue with the new way to handle deprecations

In PHPUnit 9:
```
@trigger_error
```
was ignored and
```
trigger_error
```
was marked as risky (or was failing with `convertDeprecationsToExceptions`).

The fact is that both
```
@trigger_error('User Deprecation', \E_USER_DEPRECATED);
```
and 
```
trigger_error('User Deprecation', \E_USER_DEPRECATED);
```
are reported now, when I would expect different behavior.

Because you might want to test that all the deprecation are using `@` symbol in your code.

**Comment by sensorario** [comment]
Hello! Thank you very much for this feature. Deprecations are not visible when I use `./vendor/bin/phpunit --testdox --display-deprecations`. I am doing something wrong? Or is the right behavior?

```
./vendor/bin/phpunit --version
PHPUnit 10.1-dev by Sebastian Bergmann and contributors.
```

**Comment by sebastianbergmann** [comment]
> Deprecations are not visible when I use `./vendor/bin/phpunit --testdox --display-deprecations`. I am doing something wrong?

Please do not use development versions when you're not working on PHPUnit. That being said, this is probably what #5198 is about.

**Comment by sebastianbergmann** [comment]
Superseded by #5293.
