### ISSUE TITLE
Add TestCase::registerFailureInterface() to register interface that marks exceptions to be treated as failures, not errors

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5201]
Motivated by https://github.com/phpspec/prophecy-phpunit/pull/45#issuecomment-1429853529

**Comment by sebastianbergmann** [comment]
@stof @Jean85 Any feedback on this prior to the release of PHPUnit 10.1 would be much appreciated.

**Comment by Jean85** [comment]
I've integrated it into https://github.com/phpspec/prophecy-phpunit/pull/45, thanks!
As of now though, we're still blocked by https://github.com/phpspec/prophecy/pull/585, so it's not tested under CI yet (but locally it seems to work).

As for comments, only two come to mind for now:
 * since you're using `instanceof`, it works with classes too, not only interfaces; which is good! But maybe it warrants a rename?
 * I would record FQCNs as keys, not values, to avoid duplications (multiple calls would be idempotent)

**Comment by sebastianbergmann** [comment]
> since you're using `instanceof`, it works with classes too, not only interfaces; which is good! But maybe it warrants a rename?

Makes sense, implemented in 28766f5aac456f8093a1e946aad79c9cf96bb0ca.

> I would record FQCNs as keys, not values, to avoid duplications (multiple calls would be idempotent)

Makes sense, implemented in a249d880f0d56f8fe9a8a8d2763406c9decbe521.

Thank you!
