### ISSUE TITLE
Class "App\Service\Service" is declared "readonly" and cannot be doubled

### ISSUE THREAD

**Issue by lukasojd** [sebastianbergmann/phpunit#5353]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.16
| PHP version         | 8.2.5
| Installation Method | Composer

Hello,

We've encountered an issue where mocking readonly classes is not working in the new PHP version. Is there any way to mock readonly classes? Shouldn't PHPUnit have this functionality built-in?

Thanks in advance for any help or guidance you can provide.

**Comment by sebastianbergmann** [comment]
A `readonly` class can only be extended by another `readonly` class (see https://wiki.php.net/rfc/readonly_classes#inheritance). The class that is generated for the test double needs to be mutable.

**Comment by drealecs** [comment]
I just created a PR to implement doubling readonly classes.
Just to mention here some more backstory about it in case someone might be interested in.

Recently, on some PHP 8.2 projects, I saw wasted effort with switching between classes with all readonly properties and readonly classes and (something that PhpStorm hints to) but also the other way around when a new test is added and the class is mocked.
I'm talking now about service classes, not value objects classes as usually the value objects classes should not even be doubled.
As I hate mutability and side effects, it appears that in a well organized project, almost all classes can be readonly.

It sounds like PHPUnit can improve on this and I investigated on the problem of "test doubles that are mutable" and found that their state that is mutable can be extracted outside.
The extracting logic is could use improvements and if it fits with phpunit projects plans, I think this would a solution to go forward.

After that, implementing readonly doubles that extends readonly classes was very simple and it worked nice.

**Comment by speller** [comment]
Just faced this issue. Voting for the readonly classes fix asap. The first idea in my head was to move out the state to an external mutable object when I just had read Sebastian's comments. Luckily someone already suggested a PR for this. 

I think this issue should be reopened since it targets an existing real-life problem, not solved, and has a PR.

**Comment by speller** [comment]
Any progress on this?

**Comment by speller** [comment]
> A readonly class can only be extended by another readonly class (see https://wiki.php.net/rfc/readonly_classes#inheritance). The class that is generated for the test double needs to be mutable.

@sebastianbergmann could you share your plan regarding the support of readonly classes? The only I can see is that you're closin tickets about this issue. There are no technical issues to move the state out into a separate object. We're all programmers, so the argument "generated class must be mutable" doesn't look reasonable.

**Comment by speller** [comment]
> Or your `readonly` class is a service (or processor) then that class should implement an interface and you should double that instead of the implementing class.

In my case, the class is a service and it implements an interface. But I test this class, not pass it as a double as a dependency. This class has many methods that call each other in a chain. I want to test them separately. So I create a mock and allow only specific original methods to be called. So I'm able to test these methods one by one. To test everything altogether, I use functional tests. But for unit tests, it is _a lot_ easier to test methods one by one. I can do this on a non-readonly class already. But since our policy is to use immutable services, we can not declare them readonly just because of tests.

**Comment by drealecs** [comment]
I initially hadn't thought much about readonly classes when RFC was discussed, but from my experience with PHP 8.2 so far, I can say all classes should be readonly.
Yes, I'm generalizing this a bit, but I feel like it's on the same level with "all classes should be final" as it helps with code maintainability by promoting immutability, just like final classes promoted composition.

Not talking about value objects going forward, just about service/processor classes, classes that have business logic.

Final classes require implementing an interface (or more) so that they can be replaced by some other class by using that interface type instead of the class type. Also to be able to mock them in tests, a specific case of replacing.
However, in private projects, developers are lazy and don't usually want to implement (and maintain) interfaces and also don't use final classes because of this, especially when they want to mock the class.

Unfortunately, right now it's the same with readonly classes. They require an interface so they can be mocked.
But other than mocking, you don't need an interface for a readonly class, as it can be extended and replaced by another readonly class.

So, in private projects, unlike the usage of final classes that cannot be high (due to an interface implementation requirement), the usage of readonly classes can be high.
And I would like to promote this more, but first we need to be able to mock readonly classes; and that's the reason why I tried to find a solution, as it should be something doable.

I'm pretty sure we can find a technical solution that works for the future or PHPUnit if we agree this feature is important.
Just wanted to share my thoughts and motivation for this.

**Comment by speller** [comment]
We're currently trying to utilize readonly classes as much as possible as they help in achieving the best architecture practices and make classes not allowing any statefulness by design. We have to leave some of them non-readonly only because of PHPUnit. I know that old codebases may take a long time to adopt new language features. However new projects are developed aligned with the cutting-edge language features to decrease the number of refactorings in the future. It doesn't make sense to ignore new features only because they were not existing in the past. So I hope that this specific issue will be prioritized and fixed soon. Especially, when a PR already here.

**Comment by matejthetree** [comment]
Arrived at the same problem, pretty troublesome
