### ISSUE TITLE
Using `willReturnOnConsecutiveCalls()` together with `throwException()`

### ISSUE THREAD

**Issue by Ugoku** [sebastianbergmann/phpunit#5469]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.1
| PHP version         | 8.2.8
| Installation Method | Composer

#### Summary

PHPUnit 10.3 deprecated `willReturnOnConsecutiveCalls` and `throwException` methods. I am unsure how to convert this piece of code:

```
$this->someclass
    ->method('save')
    ->willReturnOnConsecutiveCalls(
        $this->throwException(new SomeException('foo')),
        true,
    );
```

I can replace `willReturnOnConsecutiveCalls` with `willReturn`, but how can I declare that it should throw an exception the first time, and true the second time?

**Comment by sebastianbergmann** [comment]
Please note that the functionality in question is currently "only" [soft-deprecated](https://phpunit.de/backward-compatibility.html). Your tests continue to work in exactly the same way as before and no deprecation is displayed by PHPUnit. This is also the reason why the deprecation is not mentioned in the ChangeLog.

The actual deprecation for the functionality in question is tracked in #5423 and #5425.

Thank you for bringing this to my attention, I was not aware that this works:

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

interface I
{
    public function m(): bool;
}

final class Test extends TestCase
{
    public function testOne(): void
    {
        $i = $this->createStub(I::class);
        
        $i->method('m')
          ->willReturnOnConsecutiveCalls(
            false,
            true,
            $this->throwException(new Exception('message'))
          );

        $this->assertFalse($i->m());
        $this->assertTrue($i->m());

        $this->expectException(Exception::class);

        $this->assertTrue($i->m());
    }
}
```

In the example shown above, the test stub `$i` is configured so that it

* returns `false` when it is invoked the first time
* returns `true` when it is invoked the second time
* throws an exception of type `Exception` when it is invoked the third time

As of right now, I have no alternative to suggest to achieve the same result once #5424 and #5426 are implemented. I will need to investigate this further.

**Comment by Ugoku** [comment]
> Your tests continue to work in exactly the same way as before and no deprecation is displayed by PHPUnit. This is also the reason why the deprecation is not mentioned in the ChangeLog.

No, you're right about that. It's our PHPStan configuration that warns about calling deprecated methods.

Thanks for the information. I will ignore the PHPStan message for now and will keep an eye out for future changes!

**Comment by sebastianbergmann** [comment]
The soft-deprecation of `willReturnOnConsecutiveCalls()` will be reverted in PHPUnit 10.3.2.
