### ISSUE TITLE
`Only arrays and Traversables can be unpacked` exeption cannot be expected in PHP 7.4

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5499]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.11
| PHP version         | 7.4.33
| Installation Method | Composer

#### Current behavior

Under PHP 7.4, it seems `Only arrays and Traversables can be unpacked` exception is handled by phpunit and cannot be expected.

#### How to reproduce

run this test under PHP 7.4

```
    public function testExceptionExpectUnpackPhp74(): void
    {
        $this->expectException(\Throwable::class);
        $args = 1;
        strlen(...$args);
    }
```

```
1) Xxx::testExceptionExpectUnpackPhp74
Only arrays and Traversables can be unpacked

.../ModelIteratorTest.php:192
```

is displayed in the phpunit output, `TestCase::expectException()` is completely ignored.

In PHP 8.0+, the issue is not present.

#### Expected behavior

`TestCase::expectException()` must work in all cases.

**Comment by sebastianbergmann** [comment]
PHP 7.4 triggers an `E_WARNING` error for the code in question that is converted to an exception by PHPUnit's error handler.  With PHPUnit 9.6, `expectException()` cannot be used to expect exceptions raised by PHPUnit's error handler. `expectWarning()`, for instance, has be to used instead.

PHP >= 8.0 throws an exception of type `TypeError` instead of triggering an `E_WARNING`. This is why `expectException()` works for PHP >= 8.0.
