### ISSUE TITLE
Getting output as DDDD of phpunit

### ISSUE THREAD

**Issue by mj4code** [sebastianbergmann/phpunit#5520]
I am upgrading my php project to support php 8.2, so I have also upgraded phpunit to 10.3.5.
I am getting following output, does "D" means test case has been executed successfully ?
```
PHPUnit 10.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.10

DDDDDDDDDDDDD                                                     13 / 13 (100%)

Time: 00:00.043, Memory: 26.46 MB

OK, but there were issues!
Tests: 13, Assertions: 54, Deprecations: 2.
```

**Comment by sebastianbergmann** [comment]
A `D` being printed during test execution means that a test was run successfully (it did not fail), but it triggered a deprecation. This can be an `E_DEPRECATED` issue, because you are using a language feature that is deprecated in PHP 8.2. It could also be a deprecation triggered by `trigger_error('...', E_USER_DEPRECATED);`  in your code or in third-party code you depend on.

Please see https://docs.phpunit.de/en/main/error-handling.html for details.
