### ISSUE TITLE
Skipping a test during `setUp` will not dispatch test finished event

### ISSUE THREAD

**Issue by dmaicher** [sebastianbergmann/phpunit#5544]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.4.1
| PHP version         | 8.2
| Installation Method | Composer

#### Summary

I noticed that given the following test class

```php
<?php

use PHPUnit\Framework\TestCase;

class SkippedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        $this->markTestSkipped();
    }

    public function testSkipped(): void
    {
        $this->assertTrue(true);
    }
}
```

There is no `PHPUnit\Event\Test\Finished` event dispatched for the `testSkipped` test.

If I move the `markTestSkipped` into the test method itself then it is dispatched.

Is this on purpose? :thinking:

**Comment by dcondrey** [comment]
These seems intentional.

**Comment by dmaicher** [comment]
Interesting is that this worked fine with PHPUnit 8+9 and the `AfterTestHook` was called.

I noticed this when rolling back a database transaction in this extension: https://github.com/dmaicher/doctrine-test-bundle/blob/42b840b24232e71bd3fcaca712e333df20e32262/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php#L48

**Comment by bahag-schlachterk** [comment]
We just encountered the same issue when migrating our project to PHPUnit >= 10.x
In fact this behaviour also breaks the integration with PHPStorm / IntelliJ which lead to some serious confusion on our side as we could not explain this type of behaviour at first.
However this is exactly as described in the documentation:
https://docs.phpunit.de/en/11.0/writing-tests-for-phpunit.html#writing-tests-for-phpunit-skipping-tests-examples-databasetest-php
Moving the checks external dependencies (such as specific extensions or local command line tools) to setUpBeforeClass resolves the issue.

Not sure if this is a bug or just a thing that should be fixed in the documentation.
