### ISSUE TITLE
`@requires` should support `!=` for every type

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5607]
`@requires OSFAMILY != Windows` should be supported.

Currently the docs say the operators are supported for `PHP`, `PHPUnit` and `extension` version constraints only.

I belive all operators should be supported and `<`, `>`, `>=`, `<=` should emit a warning if the left/right side of the expression is non-version string.

**Comment by sebastianbergmann** [comment]
Annotations will not be changed. In fact, they will be deprecated in PHPUnit 11 and removed in PHPUnit 12.

**Comment by epdenouden** [comment]
Should also work for the new attributes, I am assuming? Couldn't find it in the manual whether `!=` is supported or not.

If it should be supported but currently isn't, might be a nice small project for me.

**Comment by sebastianbergmann** [comment]
As the argument for the `RequiresOperatingSystem` attribute is a regular expression, `#[RequiresOperatingSystem('^(?!Windows).*$')]` does what you would have expected `@requires OSFAMILY != Windows` to do back when annotations were a thing.

Whether or not we can find a better way of expressing "skip this test on Windows" should be the topic of a different issue. This issue was about the `@requires` annotation and annotations are already deprecated and will be removed in PHPUnit 12.
