### ISSUE TITLE
Where is --verbose option?

### ISSUE THREAD

**Issue by HEO4EHb** [sebastianbergmann/phpunit#5647]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | x.y.z
| PHP version         | x.y.z
| Installation Method | Composer / PHAR

**Comment by sebastianbergmann** [comment]
This is not a bug: the `--debug` CLI option was removed in PHPUnit 10.0. It is superseded by `--no-output --log-events-text php://stdout`.

However, good news: the `--debug` CLI option will make a return as an alias for `--no-output --log-events-text php://stdout`.

**Comment by sebastianbergmann** [comment]
Sorry, this was about `--verbose`, not `--debug`. `--verbose` was removed without a replacement.

**Comment by HEO4EHb** [comment]
Thank you anyway for your quick response  and for your work!

**Comment by donquixote** [comment]
> This is not a bug: the --debug CLI option was removed in PHPUnit 10.0. It is superseded by --no-output --log-events-text php://stdout.
> However, good news: the --debug CLI option will make a return as an alias for --no-output --log-events-text php://stdout.

Hello
The `-v` option in up to 9.x provided quite the clean output, reporting test method names and dataset names, but nothing else.

With `--no-output --log-events-text php://stdout` in 10.x, I get a lot of output, which is quite overwhelming:
- "Test Suite Loaded"
- "Event Facade Sealed"
- "Test Runner Started"
- "Test Suite Sorted"
- "Data Provider Method Called".
- In one project I see "Assertion Succeeded" messages, with data dumped.

Maybe I am just doing it wrong?

**Comment by frob** [comment]
Wow, this change really limits the functionality of phpUnit for TDD. I can see this being more helpful for CI deployments, but honestly, the old non-verbose seemed fine for that. I really don't see the benefit here.

Is there any way to get verbose output functionality back, either through a plugin, a wrapper, or a fork?

**Comment by okainov** [comment]
I'm migrating from old PHPUnit version and also instantly noticed it - why was `--verbose` even removed and what is the suggested alternative @sebastianbergmann ?

**Comment by alexchexes** [comment]
This is the third time **just for today** that I've looked for a solution to something related to my work with PHPUnit, found a related issue, and seen a comment from @sebastianbergmann saying that ***"X was removed without a replacement"***, immediately followed by negative reactions and complaints from users, with no further response from Sebastian.

I understand that maintainers don't owe users anything and can do whatever they want with their projects, but it's still quite surprising that the pattern

1. introduce a feature
2. remove it in a newer version without a replacement

repeats so often in this project.

**Comment by sebastianbergmann** [comment]
The `--verbose` CLI option was too coarse as it bundled unrelated concerns (runtime header, incomplete details, skipped details, TestDox timing) behind one flag.

The removal of the `--verbose` CLI option without a (single) replacement does not mean that the functionality it controlled was also removed without a replacement.

My earlier [comment](https://github.com/sebastianbergmann/phpunit/issues/5647#issuecomment-1890483283) was incorrect, for which I apologise. What I meant to say was that there is no single replacement for it, but I failed to explain this properly. You will find it below now.

In PHPUnit 9.6, the `--verbose` CLI option enabled the following:

### 1. Display runtime/configuration info at startup
- Runtime: PHP version and code coverage driver
- Configuration: Path to the PHPUnit XML configuration file being used (if any)
- Extensions: — Loaded (or failed-to-load) PHPUnit extensions (if any)

**This information is always displayed in PHPUnit >= 10.**

### 2. Display incomplete and skipped test details in the result summary

After the test run, the test runner of PHPUnit 9.6 always displayed details for errors, warnings, failures, and risky tests.
With `--verbose`, it additionally displayed details for incomplete tests and skipped tests.

**For this use case, `--verbose` has been replaced with the more fine-grained CLI options `--display-incomplete` and `--display-skipped`.**

### 3. Display timing information in TestDox output

The time a test took to execute was displayed after the TestDox output for a test.

**This is the only aspect of `--verbose` that was removed without a replacement.**

Take a closer look at the TestDox output in PHPUnit 9.6 and PHPUnit 13.0 to see for yourself that only the timing information has been lost:

#### PHPUnit 9.6, `--testdox`
```
❯ ./phpunit --no-configuration --bootstrap Email.php --testdox EmailTest.php
PHPUnit 9.6.34-4-g76dc93d1c by Sebastian Bergmann and contributors.

Email
 ✘ Can be created from valid email
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │

 ✔ Cannot be created from invalid email

Time: 00:00.037, Memory: 4.00 MB

Summary of non-successful tests:

Email
 ✘ Can be created from valid email
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

#### PHPUnit 9.6, `--testdox --verbose`
```
❯ ./phpunit --no-configuration --bootstrap Email.php --testdox --verbose EmailTest.php
PHPUnit 9.6.34-4-g76dc93d1c by Sebastian Bergmann and contributors.

Runtime:       PHP 8.5.3

Email
 ✘ Can be created from valid email [5.65 ms]
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │

 ✔ Cannot be created from invalid email [0.24 ms]

Time: 00:00.039, Memory: 4.00 MB

Summary of non-successful tests:

Email
 ✘ Can be created from valid email [5.65 ms]
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

#### PHPUnit 13.0, `--testdox`
```
❯ ./phpunit --no-configuration --bootstrap Email.php --testdox EmailTest.php
PHPUnit 13.0.2-18-g70814513c by Sebastian Bergmann and contributors.

Runtime:       PHP 8.5.3

F.                                                                  2 / 2 (100%)

Time: 00:00.005, Memory: 8.00 MB

Email
 ✘ Can be created from valid email
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │
 ✔ Cannot be created from invalid email

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

#### PHPUnit 13.0, `--testdox --testdox-summary`
```
❯ ./phpunit --no-configuration --bootstrap Email.php --testdox --testdox-summary EmailTest.php
PHPUnit 13.0.2-18-g70814513c by Sebastian Bergmann and contributors.

Runtime:       PHP 8.5.3

F.                                                                  2 / 2 (100%)

Time: 00:00.005, Memory: 8.00 MB

Email
 ✘ Can be created from valid email
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │
 ✔ Cannot be created from invalid email

Summary of tests with errors, failures, or issues:

Email
 ✘ Can be created from valid email
   │
   │ Failed asserting that two strings are identical.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'user@example.org'
   │ +'user@example.com'
   │
   │ /usr/local/src/phpunit/EmailTest.php:12
   │

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

**Comment by sebastianbergmann** [comment]
> With `--no-output --log-events-text php://stdout` in 10.x, I get a lot of output, which is quite overwhelming:
> 
>     * "Test Suite Loaded"
>     * "Event Facade Sealed"
>     * "Test Runner Started"
>     * "Test Suite Sorted"
>     * "Data Provider Method Called".
> 
> Maybe I am just doing it wrong?

You can filter the output of `--debug` from PHPUnit >= 10 using `grep`, for example, to get the behaviour of `--debug` from PHPUnit <= 9:

`./phpunit --debug | grep -E '^(Test Prepared|Test Finished)'`

`Test Prepared` is emitted immediately before your test method is called and `Test Finished` is emitted after the test runner is finished with that test method.

**Comment by alexchexes** [comment]
Thank you very much for the detailed explanation!

Regarding what I wrote above: I've since found that PHPUnit 13 introduced a replacement for `withConsecutive()`, which is great news, and that the removed `at()` can be replaced with `id()` + `after()` when it's truly needed.

Those were the other two cases that contributed to the impression I described earlier. In fact, in the cases of `--verbose` and `at()` removal, the alternatives already existed; they just weren't mentioned in the places where I ran into the "removed without replacement" message.

Sorry for the misunderstanding, and thanks again for your work on the project!

**Comment by EliW** [comment]
> ### 3. Display timing information in TestDox output
> The time a test took to execute was displayed after the TestDox output for a test.
> 
> **This is the only aspect of `--verbose` that was removed without a replacement.**

Hey @sebastianbergmann — Question about this.  Is there no way in 'non v9' now to get this detail?   I'm working on a legacy project and part of the issues have been dealing with finding slow test issues, and getting to see the runtime of each test as they run, in `--testdox --verbose` style, was extremely important in finding some bugs in our testsuite.   

Then I recently upgraded one section of our code to using phpunit 10, and suddenly found myself researching why --verbose no longer worked (and finding this ticket) :) 

I understand/respect the changes in general with --verbose having done far too much in the past, and that being broken up into separate different options now.

But is there no way in 10+ to get that 'per test timing' output like v9 would give?

**Comment by sebastianbergmann** [comment]
> Is there no way in 'non v9' now to get this detail? I'm working on a legacy project and part of the issues have been dealing with finding slow test issues, and getting to see the runtime of each test as they run

Per test runtime is available out-of-the-box through JUnit XML (since "forever") and OTR XML (since support for OTR XML was introduced).

You explicitly ask for "per test timing output" and that you can get through the [phpunit-slow-test-detector](https://github.com/ergebnis/phpunit-slow-test-detector) extension.

**Comment by EliW** [comment]
> Per test runtime is available out-of-the-box through JUnit XML (since "forever") and OTR XML (since support for OTR XML was introduced).

That is very true @sebastianbergmann ... but that does mean using XML formats.   The question was whether there was a way to replicate the "getting timing per test shown" in a standard testdox/text output.   You are completely correct that I could take the XML, and then parse it into a text output.

But it's just not the same as seeing the test times 'live' as they come through.

> You explicitly ask for "per test timing output" and that you can get through the [phpunit-slow-test-detector](https://github.com/ergebnis/phpunit-slow-test-detector) extension.

We use that, but again, it's not the same.   The slow-test-detector is a great way to see a list of slow tests that need to be touched.   But it's still not a replacement for "see the time each test took" within the context of the tests as they run.

Let me give a use-case where this was (recently) very useful to me.

We had a set of tests that in whole were running slow ... but often running them in smaller batches, was faster.  And it was extremely confusing to debug.   Run the whole suite and 10 tests pop with slow test as slow.  But run just those tests, and they were fast.    On top of that, because of some crazy bootstrapping was was being done, the 1st test you ran often would show as slow regardless of what that test was.

In the end, it was a problem of (effectively) memory leaks in the test bootstrap/framing that had been done here.  As each test ran it was polluting some global 'storage' (really class properties) with things that over time would slow down tests, dramatically.

The only way that I was able to debug what really was happening, was by looking at the output of phpunit 9's `--testdox --verbose` to see that 'per test' ms listed out from them.  And then using that to rerun classes, specific tests, just two classes back to back, etc.  And seeing in real time what was happening.

... and now because of that, we've also currently set it up that as tests run in CI, it does that --testdox --verbose as well, so that the output of the CI ... is that cleaner "one line per test" for each test run, with the 'ms' of each test out from it.  So that when a problem like this may arise again, we can look back at the test runs and see what is happening.

Esp for example, when we are (unfortunately in this case) ... having to have the slow-test detector set to something crazy like '5 seconds' because of how slow some of our expected tests will run.    But that then can hide when 10 new tests are added that are all 800ms each, then 10 more that are 1200ms, etc.  And that slowly the time to run the full suite is drifting higher to the point things begin to fail.   Without us having direct documentation as to 'why'.

## Summary

There are some useful cases to want `--testdox` style output, while having just the `(823ms)` annotation out from each test like 9's --verbose would give you.

I realize that I'm, with other people here, chatting about a change that came in phpunit 10, when it's now up to 13 ;) ... but just reality of being in the midst of upgrading old legacy codebases.

It sounds like I'm not the only one who has a valid usecase for this feature.  So it would be great if there was a good solution for those of us.

There's not really a way for us to create a modified 'output formatter' right?  so we could just make our own `testdox-timing`?   The few plugins I found that claim to do different output, really are just taking the entire output at the end of everything and reformatting it then.  Not 'as they go'.

Would be nice if it could be possible to just add a simple `--display-timing` like the other display controls, that would turn the old timing information on.

Regardless, thanks for listening, and I look forward to hearing more.   I'd be happy to look into how to add these in myself and/or create a PR for it, if given some guidance as to how best to accomplish it.  (and to understand why you might not want it to exist)

**Comment by sebastianbergmann** [comment]
> There's not really a way for us to create a modified 'output formatter' right?

You can write an extension for PHPUnit's test runner to customize its output. Here is an example.

#### Example output
```
❯ ./tools/phpunit --testsuite integration
SebastianBergmann\Raytracer\PuttingItTogetherTest::test_chapter_10 ... passed (0.853s)
SebastianBergmann\Raytracer\PuttingItTogetherTest::test_chapter_5 ... passed (1.413s)
SebastianBergmann\Raytracer\PuttingItTogetherTest::test_chapter_6 ... passed (3.776s)
SebastianBergmann\Raytracer\PuttingItTogetherTest::test_chapter_8 ... passed (4.580s)
SebastianBergmann\Raytracer\PuttingItTogetherTest::test_chapter_4 ... passed (0.039s)
```

#### `phpunit.xml` (excerpt)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/13.0/phpunit.xsd"
>
    <extensions>
        <bootstrap class="PHPUnit\ExtensionExample\Printer\Extension"/>
    </extensions>
</phpunit>
```

#### Structure
```
src
├── Extension.php
├── Printer.php
└── Subscriber
    ├── TestErroredSubscriber.php
    ├── TestFailedSubscriber.php
    ├── TestFinishedSubscriber.php
    ├── TestMarkedIncompleteSubscriber.php
    ├── TestPassedSubscriber.php
    ├── TestPreparationStartedSubscriber.php
    └── TestSkippedSubscriber.php
```
#### `Extension.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer;

use PHPUnit\Runner\Extension\Extension as ExtensionInterface;
use PHPUnit\Runner\Extension\Facade;
use PHPUnit\Runner\Extension\ParameterCollection;
use PHPUnit\TextUI\Configuration\Configuration;

final class Extension implements ExtensionInterface
{
    public function bootstrap(Configuration $configuration, Facade $facade, ParameterCollection $parameters): void
    {
        $facade->replaceOutput();

        $printer = new Printer;

        $facade->registerSubscribers(
            new Subscriber\TestPreparationStartedSubscriber($printer),
            new Subscriber\TestPassedSubscriber($printer),
            new Subscriber\TestFailedSubscriber($printer),
            new Subscriber\TestErroredSubscriber($printer),
            new Subscriber\TestSkippedSubscriber($printer),
            new Subscriber\TestMarkedIncompleteSubscriber($printer),
            new Subscriber\TestFinishedSubscriber($printer),
        );
    }
}
```
#### `Printer.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer;

use function fwrite;
use function sprintf;
use PHPUnit\Event\Telemetry\HRTime;

final class Printer
{
    private ?HRTime $startTime;
    private string $outcome;

    public function testPreparationStarted(string $testId, HRTime $startTime): void
    {
        $this->startTime = $startTime;
        $this->outcome   = 'unknown';

        fwrite(
            STDOUT,
            sprintf(
                '%s ... ',
                $testId,
            ),
        );
    }

    public function testOutcome(string $outcome): void
    {
        $this->outcome = $outcome;
    }

    public function testFinished(HRTime $endTime): void
    {
        fwrite(
            STDOUT,
            sprintf(
                '%s (%.3fs)' . PHP_EOL,
                $this->outcome,
                $endTime->duration($this->startTime)->asFloat(),
            ),
        );

        $this->startTime = null;
        $this->outcome   = 'unknown';
    }
}
```
#### `Subscriber/TestErroredSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\Errored;
use PHPUnit\Event\Test\ErroredSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestErroredSubscriber implements ErroredSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(Errored $event): void
    {
        $this->printer->testOutcome('errored');
    }
}
```
#### `Subscriber/TestFailedSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\Failed;
use PHPUnit\Event\Test\FailedSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestFailedSubscriber implements FailedSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(Failed $event): void
    {
        $this->printer->testOutcome('failed');
    }
}
```
#### `Subscriber/TestFinishedSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\Finished;
use PHPUnit\Event\Test\FinishedSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestFinishedSubscriber implements FinishedSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(Finished $event): void
    {
        $this->printer->testFinished(
            $event->telemetryInfo()->time(),
        );
    }
}
```
#### `Subscriber/TestMarkedIncompleteSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\MarkedIncomplete;
use PHPUnit\Event\Test\MarkedIncompleteSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestMarkedIncompleteSubscriber implements MarkedIncompleteSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(MarkedIncomplete $event): void
    {
        $this->printer->testOutcome('incomplete');
    }
}
```
#### `Subscriber/TestPassedSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\Passed;
use PHPUnit\Event\Test\PassedSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestPassedSubscriber implements PassedSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(Passed $event): void
    {
        $this->printer->testOutcome('passed');
    }
}
```
#### `Subscriber/TestPreparationStartedSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\PreparationStarted;
use PHPUnit\Event\Test\PreparationStartedSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestPreparationStartedSubscriber implements PreparationStartedSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(PreparationStarted $event): void
    {
        $this->printer->testPreparationStarted(
            $event->test()->id(),
            $event->telemetryInfo()->time()
        );
    }
}
```
#### `Subscriber/TestSkippedSubscriber.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\ExtensionExample\Printer\Subscriber;

use PHPUnit\Event\Test\Skipped;
use PHPUnit\Event\Test\SkippedSubscriber;
use PHPUnit\ExtensionExample\Printer\Printer;

final readonly class TestSkippedSubscriber implements SkippedSubscriber
{
    public function __construct(private Printer $printer) {}

    public function notify(Skipped $event): void
    {
        $this->printer->testOutcome('skipped');
    }
}
```
