### ISSUE TITLE
after upgrade 10.5.11 to 11.0.4, every single test marked risky with "Test code or tested code did not remove its own exception handlers"

### ISSUE THREAD

**Issue by arderyp** [sebastianbergmann/phpunit#5721]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.4
| PHP version         | 8.2.15
| Installation Method | Composer

#### Summary

After upgrading from latest 10.x to latest 11.x every single test in in my project is marked risky with `Test code or tested code did not remove its own exception handlers`.  Before the upgrade, all tests passed via the same command without warnings of any kind.

#### Current behavior

All tests marked risky with `Test code or tested code did not remove its own exception handlers`

#### How to reproduce

I am not sure what's causing it. I do use a custom Extension, but not any handlers. I use a few third party extensions as well. If I `var_dump($activeErrorHandlers)` [here](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L1879) I get the following:

```
array(1) {
  [0]=>
  object(PHPUnit\Runner\ErrorHandler)#1135 (3) {
    ["baseline":"PHPUnit\Runner\ErrorHandler":private]=>
    NULL
    ["enabled":"PHPUnit\Runner\ErrorHandler":private]=>
    bool(true)
    ["originalErrorReportingLevel":"PHPUnit\Runner\ErrorHandler":private]=>
    int(-1)
  }
}
```

Have I perhaps misconfigured something or might this be a bug or some sort? Potentially related https://github.com/sebastianbergmann/phpunit/issues/5403

**Comment by JE4GLE** [comment]
Same for me, an update would be nice. 11.0.3 also throws the error

**Comment by michaljusiega** [comment]
If you use Symfony in your tests, see: https://github.com/symfony/symfony/issues/53812

**Comment by arderyp** [comment]
Thank you @michaljusiega, that may very well be my issue!

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by arderyp** [comment]
thanks @sebastianbergmann, and @michaljusiega, and @derrabus 

@derrabus 's suggestion [here](https://github.com/symfony/symfony/issues/53812#issuecomment-1962740145) solved the problem for me. So, I will close this, as it's not a phpunit issue.

**Comment by pallad42** [comment]
I think I have found a solution for this case, I have described it here -> [https://github.com/laravel/framework/issues/49502](https://github.com/laravel/framework/issues/49502)

---

PHPUnit 11.5
PHP 8.2
Symfony 6.4

The suggested solutions didn’t work for me, but I found a way to bypass the problem. The only solution that worked was to mark each method in `KernelTestCase` and `WebTestCase` with the `#[RunInSeparateProcess]` attribute. This way, each test runs in a separate, isolated process, so the handlers from previous tests are not overwritten. I’m not sure if this solution is correct or efficient, but I spent many hours debugging and couldn’t come up with anything better.

So instead of using `dama/doctrine-test-bundle`, I handle transaction rollbacks manually. I think DAMA doesn’t work properly when tests are executed in isolated processes.

KernelTestCase
```php
protected function setUp(): void
{
    parent::setUp();
    $kernel = self::bootKernel();

    $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();

    $this->entityManager->beginTransaction();
    $this->entityManager->getConnection()->setAutoCommit(false);
}

protected function tearDown(): void
{
    parent::tearDown();

    if ($this->entityManager->getConnection()->isTransactionActive()) {
        $this->entityManager->rollback();
    }

    $this->entityManager->close();
}

#[RunInSeparateProcess]
public function testSomething() { ... } // test method will run inside a DB transaction and roll back at the end
```

WebTestCase
Unfortunately, neither `DAMA` nor the `KernelTestCase` approach worked in this case. The only solution I found was to use the following (it is not efficient way, but it works):
```php
protected function setUp(): void
{
    parent::setUp();
    $this->client = static::createClient();
    $this->entityManager = static::getContainer()->get(EntityManagerInterface::class);
    exec('php bin/console doctrine:fixtures:load --no-interaction --env=test');
}

#[RunInSeparateProcess]
public function testSomething() { ... } // database will be overwritten with fixtures before each test
```
Maybe consider experimenting with the `liip/test-fixtures-bundle` package — it might work, although I haven’t tested it.

**Comment by arderyp** [comment]
Thanks for the info, but that's also just another workaround, and a particularly thorny one at that. As you mentioned re DAMA, running tests in separate processes could have major impacts for certain setups
