### ISSUE TITLE
Allow attributes for code coverage targeting to also be used on the test method level (instead of only on the test class level)

### ISSUE THREAD

**Issue by neclimdul** [sebastianbergmann/phpunit#5837]
[CoversMethod](https://github.com/sebastianbergmann/phpunit-documentation-english/issues/340) was helpfully added however it only allows targeting classes. In the discussion leading up the interest seems to have been for targeting methods.

https://github.com/sebastianbergmann/phpunit/issues/5175#issuecomment-1963380677
https://github.com/sebastianbergmann/phpunit/issues/5175#issuecomment-2070313770

For me, this feature was useful in previous versions for making coverage reports explicit as well as to see when a test is maybe not needed or needs to be updated because a method name changes similar to `{@inheritDoc}` or `#[Override]` adjusted for tests.

It would nice if this was also allowed.

**Comment by sebastianbergmann** [comment]
To me, allowing attributes for code coverage targeting to also be used on the test method level does not make sense.

**Comment by neclimdul** [comment]
OK but... Drupal uses it and ever project I work on does so... other people are using it.

**Comment by kubawerlos** [comment]
@neclimdul maybe you could elaborate when it is useful, technically. Claiming "other people are using it" is not really an argument. Millions of flies can't be wrong, right?

I have never used it (maybe it would be useful in some projects I worked decade ago, but they had no test at all). I believe if you are following SRP then coverage on a class level is enough.

**Comment by neclimdul** [comment]
Sure, my "but people are using this" response was mostly a frustrated "this was closed without any discussion WTF" response. I'm still pretty frustrated because people in the original issue are requesting it, I'm requesting it, seems like there's interest so maybe would could have at least discussed before closing it.

Frustrating aside, to your question, as mentioned in the summary its useful for explicitly flagging what the test method is intended to test. This has some benefits

 1. You can see what code it testing your method when reviewing a method even if the call is indirect.
 2. You can quickly link back to the code you're testing in your IDE.
 3. Your coverage test doubles to make sure you're not trying to cover code that no longer exists. This may seem uncommon because your test _should_ be calling the method you're testing. However this has flagged dead tests for me quite a few times and the amount of time I've spent tracking broken tests on projects to code that hasn't existed for multiple versions tells me this is actually valuable.
 4. Reports can be cleaner. If you have a class that has two methods and a couple hundred provided arguments, if you have any interaction between the methods you get these crazy big reports where you get cross coverage that makes detailed reports kinda useless. A specific XSS class comes to mind which has a test and a filtering method and thousands of test cases. The test is better by being able to split the tests and the report is exponentially smaller by being able to assign the coverage.

I think this generally starts being useful in more complicated systems where there's "magic" happening.  Drupal has a lot of this but I _really_ appreciate this when writing tests for Laravel which more people here might be familiar with. Here's an overly simplified test that would test a Controller in Laravel:

<?php

use Illuminate\Foundation\Testing\TestCase;

/**
 * @coversDefaultClass \App\Http\Controllers\ContactController
 */
class FooControllerTest extends TestCase {
    /**
     * @covers ::index
     */
    public function testIndex() {
        $response = $this->get('/api/v1/foo');
        // Assertions...
    }
}
?>

Without the @covers to explicitly link there is no way to see what this is covering. With it, my IDE shows this code in the usage list for index, I can quickly navigate to the code being tested though the docblock, the method doesn't show up as "unused", and if the method name changes but it passes (maybe in a unexpected way)  the coverage report catches it and forces a review.

Testing controllers with coverage is pretty useful but a _little_ weird but this sort of indirect call in testing can happen for a lot of reasons. Testing container interactions, code running in events, testing queue systems, etc.

So yeah, I think in an ideal world this wouldn't be useful. But in reality I find it incredibly useful.

**Comment by ipontt-neering** [comment]
I've taken to writing 1 class per method in tests and for this use case, `#[CoversMethod]` as it currently is works. It might seem overkill for very small controllers but this approach can be really useful when dealing with legacy code.

Also, for a generic api rest controller (index, store, show, update, destroy), it can easily end up with at least 3 tests per method just to check status codes. Then you might have additional functionality you need to test for query strings in the index and show methods. And all the validation you might want to test for the store and update endpoints. I'll admit I liked the `@covers ::method` syntax, but I can see my test classes becoming easier to deal with like this.

**Comment by alexekorn** [comment]
I may be kicking a dead horse here, but I'm curious about best practices in PHPUnit and how this interacts with `CoversMethod`. I think a better shared understanding of best practices here would be helpful.

In the PHPUnit documentation, there are multiple places that hint at there being one `TestCase` per class being tested:
1. > The tests for a class `Greeter` go into a class `GreeterTest`.

    https://docs.phpunit.de/en/11.3/writing-tests-for-phpunit.html#asserting-return-values

2. > Looking at this project’s directory structure, we see that the test case classes in the `tests/unit` directory mirror the package and *class structure* of the System Under Test (SUT) in the `src` directory [emphasis mine]

    https://docs.phpunit.de/en/11.3/organizing-tests.html

If the documentation recommends that there is one `TestCase` per class, and a class can have multiple methods, then it would make sense to me that `CoversMethod` could also live on the test method level.

However, I see that in the PHPUnit test code, there is indeed one `TestCase` per *method*: [here is an example](https://github.com/sebastianbergmann/phpunit/blob/main/tests/unit/Framework/Assert/assertArrayHasKeyTest.php) of the `TestCase` for `Assert::assertArrayHasKey()`.

If I'm using the documentation as best practices, I think it makes sense to support `CoversMethod` on the test method level. If the best practice is to have one `TestCase` per method, then the documentation should be updated to reflect this best practice.

(Full disclosure: I selfishly would like `CoversMethod` support on the test method level since our codebase uses one `TestCase` per class, not per method, and therefore a `TestCase` frequently covers many methods. But I don't want to fight against best practices, so if we've been misunderstanding them or they're changing, we'll update our codebase as necessary to align.)

**Comment by zeleznypa** [comment]
In PHPUnit 9, it was possible to have a "TestCase" with more than one "Test".

Each test can test a part of the class (a method).

The test method can traverse more lines of the class, but it is designed to test just one method. So the coverage of this "test" can be defined with @covers ::methodName, which cleans up "false positive" coverage.

Unfortunately, the Attribute replacement kills the "TestCase" and forces developers to use them just for one "Test", refactor all the current code to a bunch of needless files, or sacrifice the proper code coverage?

What is the "Best practice" on "One test per TestCase"?
