### ISSUE TITLE
Mocked method called in constructor and a additional method throws an unexpected exception

### ISSUE THREAD

**Issue by sbuerk** [sebastianbergmann/phpunit#5857]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.2.0
| PHP version         | 8.2, 8.3
| Installation Method | Composer + phpunit repo directly

#### Summary

A class method is called in the constructor and in other
class methods. Using `onlyMethods()` to mock that method
does not regonized the calling (count) until now, but at
least subsequential calls could be tested and ensured.

This worked until 11.2.0 of phpunit and was detected in
the TYPO3 nightly pipeline automatically pulling in new
dependency versions, like phpunit.

Note: In manual tests this has been reduced to phpunit
and other dependency ruled out. Can be reproduced within
the phpunit source code directly.

#### Current behavior

Since 11.2.0 this no longer works and a exception like following
is thrown:

```
Error: Typed property MockObject_ClassCallingMethodInConstructor_b5ada611::$__phpunit_state
must not be accessed before initialization
```

#### How to reproduce

This can be reproduced with a simple class:

```php
<?php declare(strict_types=1);

namespace Vendor\Package;

class ClassCallingMethodInConstructor
{
    public function __construct()
    {
        $this->reset();
    }

    public function reset(): void
    {
    }

    public function second(): void
    {
        $this->reset();
    }
}
```

and having a test like following:

```php
use Vendor\Package\ClassCallingMethodInConstructor;

public function testOnlyMethodCalledInConstructorWorks(): void
{
  $testClassMock = $this->getMockBuilder(ClassCallingMethodInConstructor::class)
     ->onlyMethods(['reset'])
     ->getMock();

  $testClassMock->expects($this::once())->method('reset');
  $testClassMock->second();
}
```

#### Expected behavior

Test passes without error (green), which worked until 11.2.0.

**Comment by sebastianbergmann** [comment]
PHPUnit 11.2 has added support for extendable classes that are declared readonly. This required extensive changes to the runtime internals of the test double functionality. These changes are the reason why tests like the one you have provided as an example no longer work. I am grateful to you for reporting this, as I was not aware of this problem before.

Side note: maybe we can talk about this at the TYPO3 code sprint this week, whether the TYPO3 project can also test in its nightly CI pipeline with the current development version of PHPUnit. This would allow us to uncover such problems earlier.

The problem you found is ultimately due to the fact that the test double functionality of PHPUnit supports not only interfaces, but also extendable classes. The fact that only a selection of the methods of an extendable class can be replaced makes the whole thing even worse.

Please don't get me wrong, I don't want to deny any blame, nor do I want to blame users of PHPUnit. The only person I blame is myself and I am sorry that PHPUnit 11.2 broke your tests.

I will try me best to fix this issue, but at least right now I am not very hopeful that it can be fixed (without reverting #5804).

**Comment by sebastianbergmann** [comment]
I have an idea how to solve this, now I need to find time to give it a try.

**Comment by garvinhicking** [comment]
> Please don't get me wrong, I don't want to deny any blame, nor do I want to blame users of PHPUnit. The only person I blame is myself and I am sorry that PHPUnit 11.2 broke your tests.

Just dropping by to say that there's no blame at all, and those nightly tests are there for us to catch things early, and search for solutions. Thank you and @sbuerk for inspecting this so quickly, and I'm sure there'll be a solution. :-)

**Comment by sebastianbergmann** [comment]
Brief update: The confidence Garvin has shown me that I will be able to solve the problem has motivated me to continue thinking about the problem and working on a solution.

I currently have the situation here (local, not committed and pushed) that @sbuerk's test is green. Whoopee! However, several other tests are red. Oh no!

Let's hope that I manage to turn all the tests green again ...
