### ISSUE TITLE
Allow different file name to class name mapping

### ISSUE THREAD

**Issue by julienfalque** [sebastianbergmann/phpunit#5878]
I'd like to have my tests stored in the same directory as tested code, similar to Jest convention, e.g.:
* `src/Foo.php` → production code, contains a `Foo` class
* `src/Foo.test.php` → test code, contains a `FooTest` class that covers `Foo`

Currently, this is not possible because PHPUnit assumes that the test class name is what appears before the first dot in the filename, so for `Foo.test.php` it looks for a `Foo` class, which is not in that file.

Do you think it would make sense to give more control on the way PHPUnit infers test classes from files?

**Comment by sebastianbergmann** [comment]
In other words: the `suffix` attribute of the `<directory>` element under the `<testsuite>` element of PHPUnit's XML configuration file does not support this use case:

#### Example Project Structure
```
.
├── phpunit.xml
├── src
│   ├── autoload.php
│   ├── Foo.php
│   └── Foo.test.php
└── tools
    ├── phpunit
    └── phpunit.phar -> phpunit
```
#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.2/phpunit.xsd"
         bootstrap="src/autoload.php"
>
    <testsuites>
        <testsuite name="default">
            <directory suffix=".test.php">src</directory>
        </testsuite>
    </testsuites>
</phpunit>
```
#### `src/Foo.php`
```php
<?php declare(strict_types=1);
namespace example;

final readonly class Foo
{
    public function doSomething(): true
    {
        return true;
    }
}
```
#### `src/Foo.test.php`
```php
<?php declare(strict_types=1);
namespace example;

use PHPUnit\Framework\TestCase;

final class FooTest extends TestCase
{
    public function testSomething(): void
    {
        $foo = new Foo;

        $this->assertTrue($foo->doSomething());
    }
}
```
```
$ ./tools/phpunit
PHPUnit 11.2.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.8
Configuration: /home/sb/5878/phpunit.xml

There was 1 PHPUnit test runner warning:

1) Class Foo cannot be found in /home/sb/5878/src/Foo.test.php

No tests executed!
```
In the configuration shown above, `<directory suffix=".test.php">src</directory>` instructs PHPUnit's test runner to recursively search the `src` directory for files with filenames ending in `.test.php`. This works.

However, the test loader expects a class named `Foo` to be declared in `Foo.test.php` (instead of `FooTest`).

This is just an explanation of how the status quo works. The simplest thing that could possibly work that I can think of would be to look for a class for which the class name starts with `Foo` (`Foo.test.php` with stripped of suffix `.test.php`) and which extends `TestCase`.

I am not convinced (yet) that this is a good idea. Therefore, I will not work on implementing this myself. I will, however, consider a pull request that implements this.

**Comment by julienfalque** [comment]
What about a new config to provide a PHP callable that would replace `TestSuiteLoader::classNameFromFileName()`? Maybe limited to a list of built-in callables?

**Comment by localheinz** [comment]
Also see https://localheinz.com/articles/2023/03/03/organizing-test-code-in-php/.

**Comment by sebastianbergmann** [comment]
@theseer, @localheinz, @staabm, @Schrank, @sebastianheuer, @Tesla91, and I discussed this issue during the PHPUnit Code Sprint in Munich today and came to the conclusion that this use case should not be supported.
