### ISSUE TITLE
Testdox no longer outputs in real-time

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#5883]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.24
| PHP version         | 8.2.15
| Installation Method | Composer

#### Summary

The sole reason I enabled testdox in PHPUnit 9 was for the immediate result output. For long-running test suites, displaying dots is not the level of immediate feedback we want from a test runner. Moreover, some CI runners (including GHA) do not emit lines until the newline character is reached, and some other CI services (like classic Travis CI) will fail a build if it doesn't receive a (complete) log line within a certain timeout. Testdox solved all these problems in PHPUnit 9 with immediate test result output.

#### Current behavior

In PHPUnit 10, testdox has no bearing on the test runner, other than printing a report at the end.

#### How to reproduce

`--testdox` or `testdox="true"`.

#### Expected behavior

Print results in real-time.

**Comment by sebastianbergmann** [comment]
This works as intended.

The purpose of the TestDox output is documentation, not "real-time output" and/or being a replacement for the regular output.

**Comment by Bilge** [comment]
That's awful, but it's your software. Normally, when I "upgrade", I expect my suite of options to expand, not decrease. We have now lost the only out-of-the-box way to have real-time test output.

**Comment by warpr** [comment]
Is there any other way to see the names of the tests being run in real-time?  The dots don't provide any useful info while tests are running.

**Comment by kAlvaro** [comment]
@warpr As far as I know there is only `--debug`, though it is a little bit more cluttered and certainly not as visual.

@sebastianbergmann May I humbly suggest you reconsider this as quality of life improvement, as long as it doesn't create too much maintenance burden? I find real-time texdox output useful in two contexts:

- While writing or fixing tests locally (or working on a feature and using tests to verify it works), when you typically need to run them many times in a row, it gives a useful progress highlight. Quite often, you don't need to run the whole set if you spot a common pattern in failures (&laquo;Oops, I made a typo in data provider argument name&raquo;).
- When running lengthy CI pipelines (e.g. GitLab), it allows to determine whether a given test (related to the feature you've just worked on) passes without having to wait for the whole job to finish. That allows to abort the job and get back to work (if fail) or grunt with satisfaction and switch to another task (if pass). In theory, tests that pass locally will also pass in CI. In practice, percentage is not 100% because infrastructure is complicated.

We can certainly use `--debug` for that, but if the rationale to remove real-time output is that TestDox is for documentation, we can equally argue that debug is for debugging.

**Comment by sebastianbergmann** [comment]
TestDox was never and is not intended for use in Continuous Integration environments. TestDox is intended as an output of documentation/specification, e.g. in the context of the TDD feedback loop.

If you want to know "where it hangs", then --debug is the better choice. However, as you already observed, this is only intended for debugging, not as "normal" output.

I think that "output in CI pipelines" is a separate use case and as such should be addressed using a new/separate output printer. I do not know yet whether this new output printer has be provided by PHPUnit out-of-the-box or whether it should be an extension instead.

**Comment by Bilge** [comment]
I would consider writing that printer. I [did so already](https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer) back in PHPUnit 5/6 days. I would be happy to work with you to massage its output into a format we're both happy with.

**Comment by kAlvaro** [comment]
@Bilge Not sure who you were addressing to. I wrote my two personal use cases in my [previous comment](#issuecomment-2219854365). It makes sense to separate progress/results/logging formats (never thought about it because it worked in previous versions), and from a quick grasp it seems you don't really need a lot of code to have a basic real-time printer. Fine-tuning displayed data and styles can consume endless hours, though. TestDox with ANSI colours is highly visual and it'd be awesome if internal code could be reused, but no idea if that's possible.

**Comment by Bilge** [comment]
I was addressing @sebastianbergmann but he seems to have [other ideas](https://github.com/sebastianbergmann/phpunit/pull/5895).

**Comment by Ghustavh97** [comment]
Why is every version since 9 going down hill and removing soo many features?
